### ISSUE TITLE
set up automatic builds

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/Play#1]
- [x] automatic build for each commit & pr
- [x] github integration
- [x] require successful build before merging
- [x] build logs publicly available
- [x] use same code / script for local builds where possible
- [x] upgrade travis to be used from a webhook or as a Github App
- [x] upload windows travis build artifacts upon commit to master.

**Comment by Baklap4** [comment]
Another needed thing is to cache `Unity-2018.1.4f1` unless a newer version is found remote. This will decrease the build time.

**Comment by basisbit** [comment]
build currently fails because with unity 2018.1 it now is impossible to activate the unity install using a personal license. There exists a workaround: create and use a pre-activated docker image

**Comment by basisbit** [comment]
others already worked on figuring out how to use unity + docker in travis-ci with personal license: http://www.robinryf.com/blog/2017/09/30/running-unity-inside-docker.html

**Comment by Baklap4** [comment]
Travis should also be updated to be spinned up by using webhooks or installed as an app. This is because services (as it's now configured) are getting deprecated on the **first of october.**. 

> GitHub plans on shutting down GitHub Services so we can shift focus to other areas of the API, such as strengthening GitHub Apps and GraphQL, and improving webhooks. The intention of GitHub Services was to allow third-party developers to submit code for integrating with their services, but this functionality has been superseded by GitHub Apps and webhooks. GitHub Services has not supported new features since April 25, 2016, and we plan to officially deprecate it on October 1st, 2018.

![image](https://user-images.githubusercontent.com/3918517/42352082-a95fba3c-80b8-11e8-9122-88263d34efed.png)

**Comment by Baklap4** [comment]
Upload travis artifacts (windows, osx, linux) to github upon tag creation would be enough to setup our first kind of continuous deployment

**Comment by basisbit** [comment]
@achimmihca for your information: TravisCI automated build-check and-testcase-execution is finally working again. I'll re-enable passing the TravisCI-build check integration as requirement before merging a pull-request, if you are ok with that?

**Comment by achimmihca** [comment]
Nice to hear that!
Does the automatic build also create an executable? I mean, is the Unity build started for some target platform?

It would be nice to have a link to the UltraStar Play nightly version for windows / linux / mac. Note that this nightly should also include needed game resources such as I18N files.

**Comment by basisbit** [comment]
Build of each master branch commit now finally works! here is a build of 43c0d8b:
http://ultrastar.public.basisbit.s3.amazonaws.com/UltraStar-Deluxe/Play/150/150.3/UltraStarPlay-build.tar.gz

**Comment by Baklap4** [comment]
Heey i haven't been following closely, but i see there's loads going on here at UltraStar Play! Good to see! Does this also build pull requests, so the reviewer and or tester can test it with a 'working' latest copy?

**Comment by basisbit** [comment]
Hi, @Baklap4! Pull requests are automatically unit-tested and built, but build artifacts are only uploaded to AWS for master branch commits. Otherwise, anyone could create a malicious pull request to either get some of the credentials used for the build-bot or to host malware and so on.
In the Travis-CI [docs](https://docs.travis-ci.com/user/uploading-artifacts/), there is a note about this at the beginning of the page: `Note that the artifacts addon is not available for pull request builds.`

**Comment by Baklap4** [comment]
Check, i'm just gonna link the issue here just for reference: https://github.com/travis-ci/travis-ci/issues/5579

**Comment by basisbit** [comment]
The build-bot should be good enough for now. Any further improvements can be tracked in separate issues. Also, we should start creating unit tests and integration tests, so regressions are easier to spot.
