### ISSUE TITLE
implement audio playback

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/Play#10]
- playing an audio should be as easy as one line of code.
- maybe something like Audio.play(Theme.getResource(ETheme.BackgroundMusic), EAudioBehaviour.StopAnyOther, ELoundness.Max)
- This will be used to play button click sounds, background music, notification sounds, and other background audio.
- method for stopping audio playback (not sure if pause/play capability is required)

**Comment by achimmihca** [comment]
There is already API in Unity to play audio, namely [AudioSource.Play](https://docs.unity3d.com/ScriptReference/AudioSource.Play.html). An AudioSource is linked to an AudioClip, which contains the raw waveform data loaded from a sound file. The AudioSource handles additional things like volume.

**Themes**

You seem concerned with theming in much of your code design and several issues here on GitHub.
For me, this is something orthogonal to the functioning of a button. The Button Component of a GameObject can have an associated AudioSource that is played on click. However, it should not bother with chaning this sound for different themes.

Changing Assets (e.g. AudioClips, images, fonts) based on a theme can be implemented by a separate Component, for instance a ThemeableAudio, ThemeableImage or ThemeableFont. These could extend a common base class Themeable. A ThemeableAudio next to a Button could swap its AudioClip as needed. The Button does not care.

A ThemeManager could iterate over all Themeable in the current scene to trigger the change of Assets.
I implemented something similar for internationalization. The I18NManager will update all I18NText Components according to the current language. The I18NText will update the UI Text Component, which does not know of any internationalization. Take a look at the I18NDemoScene to get an idea.

For loading assets dynamically at runtime, see https://docs.unity3d.com/ScriptReference/Resources.Load.html
