### ISSUE TITLE
Remove voice from songs with Spleeter

### ISSUE THREAD

**Issue by manureini** [UltraStar-Deluxe/Play#106]
Issue type: Development discussion

### Problem or question to be solved
There could be an option to remove all voice from an song to get "real" karaoke songs.

### Suggested solution/s
 -> https://github.com/deezer/spleeter

### Your opinion on the topic
Would be a great feature ;)

**Comment by basisbit** [comment]
Thank you for this feature request! Spleeter definitely looks interesting and helpful for song creators. We will probably not add spleeter (plus all its dependencies) directly into the UltraStar Play game as that would complicate or break OS/platform-independence, but spleeter might be a good addition which could be shipped in a song creator tool package / bundle for windows and linux.
For now, I added it to the tools section of our wiki: https://github.com/UltraStar-Deluxe/Play/wiki/Tools

**Comment by basisbit** [comment]
@bohning this tool might be interesting for UltraStar Creator, too.

**Comment by achimmihca** [comment]
Spleeter would also be useful in the song editor (pitch detection, timing) because it separates the voice from the rest of the music. Pretty impressive AI stuff.

**Comment by achimmihca** [comment]
If you want to try Spleeter, there is a simple to use GUI app for Windows: https://makenweb.com/SpleeterGUI
Further, there are some online services that use spleeter under the hood. I tried this and it produces the same output: https://vocali.se

**Comment by achimmihca** [comment]
I implemented the Spleeter integration successfully for the upcoming Steam release.
It can be used in the singing game to mute the voice of the music, similar to classic karaoke.

Furthermore, I also added speech recognition via Vosk, which can be useful for creating new songs.

For now, I did the implementation in a private repository.
