### ISSUE TITLE
implement synced audio and video playback

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/Play#11]
%todo%

**Comment by achimmihca** [comment]
I implemented this.
However, I use NAudio to play external MP3 files as well. NAudio seems to be Windows / .NET lib only.

Current task: look for cross platform way to play external MP3 files in Unity.
Mp3Sharp might be an option.
See also: 
https://answers.unity.com/questions/517837/how-to-play-mp3-mp4-files-on-the-local-disk.html
https://forum.unity.com/threads/importing-audio-files-at-runtime.140088/

**Comment by achimmihca** [comment]
Another issue: not all video formats that are working in UltraStar Deluxe will work in Unity.
For example, I have an mkv file that works in USDX, but not in Unity.

Anyway, converting the video file to mp4 is probably the easiest workaround for now.

**Comment by basisbit** [comment]
Honestly, why don't we instead offer tutorials / tools for converting the usual formats to whatever almost all Unity targeting platforms support? This is typical nowadays for various other games, and it would also force the various communities to not use various broken and old formats any more.
Maybe we should suggest use of these formats (not blocking other formats, if they are supported on the local system):
audio: ogg
video: h264 mp4

**Comment by achimmihca** [comment]
There is also an issue with NAudio when playing MP3 files with changing sample rates. Error message:
`Got a frame at sample rate 24000, in an MP3 with sample rate 44100. Mp3FileReader does not support sample rate changes.`

**Comment by basisbit** [comment]
Created a wiki page for the media file formats topic: https://github.com/UltraStar-Deluxe/Play/wiki/Converting-song-media-files

**Comment by basisbit** [comment]
For mp3 file decoding -> playback on all target platforms, we could use https://github.com/naudio/NLayer . It is fully managed C# code, MIT licensed, and thus should work for our usecase if it is efficient/fast enough.

**Comment by basisbit** [comment]
UltraStar Play now supports the most common audio file types and also the most important video file types. Thus, this issue can be closed now. The documentation in the wiki is now also updated.
