### ISSUE TITLE
Recorded note does not give points when its sentence is not displayed

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#112]
### Actual behaviour

It is possible to set a delay for mic input, such that notes are recorded for positions earlier than the current playback position.
When using a high delay value, before the grading of the last syllables of a sentence happens, it switches already to the next sentence and apparently does not give points for the last syllables of the previous sentence.

### Expected behaviour

The notes should give points, even if the notes are not for the currently displayed sentence.

### Steps to reproduce

- Set a high mic delay (e.g. 500ms).
- Sing a sentence
- Notice how the last 500ms of the sentence are not counted, even though the notes are recorded for this delay.

### Additional Notes

The issue has been noticed in #108

**Comment by achimmihca** [comment]
@basisbit 
Where does USDX consider the mic latency? Only for recording notes, or also for displaying notes and the lyrics position indication?
I noticed that there is a mismatch in USPlay when the position indication is perfectly in sync in USDX and vice versa. This is very well visible in the song editor.

When I open the audio in audacity, it seems that USPlay is correct. So it seems that USDX is considering a latency for the lyrics position indication.

How can I set the latency setting to 0 in USDX to counter check this?

**Comment by basisbit** [comment]
on Windows and other systems where USDX uses basslib, by default the audio device is asked for an estimated latency and that is used for adjusting for which "beat" the recorded audio is to be considered for grading. In the config.ini and in current versions of USDX (a build from 2019 or newer), this can be set up per soundcard.
The relevant key is "Latency" and is located in the "Record" section of the ini. Default value is -1 for LATENCY_AUTODETECT. The value can be changed and is to be specified in ms.

**Comment by basisbit** [comment]
the Lyrics position indication is to show what the singer should be singing right now. So it is current audio frame position plus configured video playback delay minus configured audio playback delay.

**Comment by achimmihca** [comment]
Aha! Then I am looking for video playback delay and audio playback delay, where can I find these? config.ini does not seem to have these fields.

Shouldn't video playback delay and audio playback delay be negligible?

**Comment by basisbit** [comment]
From [UIni.pas:](https://github.com/UltraStar-Deluxe/USDX/blob/master/src/base/UIni.pas#L1445)
> AVDelay := IniFile.ReadInteger('Game', 'AVDelay', 0);
> MicDelay := IniFile.ReadInteger('Game', 'MicDelay', 140);

ReadInteger arguments are 1. in what section it should search for the setting, 2. name of the setting, 3. default if nothing is specified.

The Soundcard dependent config is
> DeviceCfg.Latency := IniFile.ReadInteger('Record', Format('Latency[%d]', [DeviceIndex]), LATENCY_AUTODETECT);
