### ISSUE TITLE
Change the video gap by dragging horizontally on the video area in the song editor

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#119]
The video and music of a UltraStar song can be out-of-sync (e.g. when the music and video file come from different sources). The #VIDEOGAP tag is used to synchronize these tracks. Thus, it should be possible to edit the #VIDEOGAP in the song editor.

The editor could have a feature to fine-tune the video gap. Adjusting the video gap via drag gesture provides a precise and intuitive control. For this to work, the dragging motion has to change the displayed frame of the video immediately.

When the user hovers over the video, the cursor should change to indicate that a drag gesture is possible. There is already such an icon, which is used for the drag gesture to stretch notes.

I would suggest to implement it as (1 second = width of video area) or maybe (1 second = width of window).

What I imagine is that the user plays the song, then pauses where the video gap is clearly visible (typically this is pretty obvious when people in the video are opening their mouth to start singing). The playback position is set to this point. Then the video area is dragged until the displayed frame matches the playback position of the video.

**Comment by basisbit** [comment]
The `#VIDEOGAP` exists only to separate fix video track and audio track being out of sync. This should be the case only very very rarely, and only when the audio file is from a different original source than the video file. What you might want to instead use is `#GAP`, to fix the ultrastar txt file not being in sync with your media files - which happens often when the media file is not exactly the one which thetxt file creator used.

`#VIDEOGAP` should never be used for working around a bad setup where the TV latency is greatly different from the audio playback difference.

**Comment by bohning** [comment]
> The `#VIDEOGAP` exists only to separate fix video track and audio track being out of sync. This should be the case only very very rarely, and only when the audio file is from a different original source than the video file. What you might want to instead use is `#GAP`, to fix the ultrastar txt file not being in sync with your media files - which happens often when the media file is not exactly the one which thetxt file creator used.
> 
> `#VIDEOGAP` should never be used for working around a bad setup where the TV latency is greatly different from the audio playback difference.

Exactly right.

**Comment by achimmihca** [comment]
>The #VIDEOGAP exists only to separate fix video track and audio track being out of sync

And this is exactly what I want to do.

> This should be the case only very very rarely

1. does not matter. This is an editor for UltraStar songs so ideally it should be possible to edit every aspect of the file.
2. It is not rare that a #VIDEOGAP is needed. I have about 400 songs in my lib and about 50 of them have a #videgap != 0, which is about 12.5%. I would argue that it is likely you need a videogap as soon as your audio and video file do not come from the same source. For example, consider you have a video from YT and a music track from CD (or any other combination of sources).
3. It is not due to a "bad setup" of my hardware. Obviously every other video I watch has perfectly synchronized audio and video (YouTube, movies, TV etc.)

My concrete use case is that I have a UltraStar Disney song in Spanish. And want to create the German version of the song. This includes changing the lyrics and syncing music and video just a little bit.

> What you might want to instead use is #GAP

No, I already added a button in the song editor to set the GAP to the current playback position (very helpful!).

> which happens often when the media file is not exactly the one which thetxt file creator used.

Assuming this, then I argue that it is just as likely that also the video file is distributed separately from the txt file. Hence, the need for changing the #GAP is as likely as changing the #VIDEOGAP, except that a synchronized video is irrelevant for game play.

---
I think I mis-phrased the motivation behind this issue. Sorry for that. I just want to edit the #VIDEOGAP in the song editor with immediate feedback for the user.

**Comment by basisbit** [comment]
Maybe I should have phrased my response differently... This was meant to be more of a hint, because I regularly see people misusing #videogap to work around the latency from the TV doing "fancy image enhancing stuff".

The cases you mentioned are of course valid use cases for #videogap
