### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#127]
A first release of the project is planned. For future releases, it would be useful to show users a notification about new versions. Of course even cooler would be an auto-update feature, but I guess a notification is easier and will do for the moment.

### Where to show the notification

I would show a pop-up dialog in the MainScene. The warning dialog (see UiManager) could be re-used for this.

### Opt-out for new versions

The user should be able to discard the notification with an option to ignore this particular release or all new releases (like "Remind me next time", "Do not remind me again of this version", "Do not remind me again of this version or any other future version").

The "do not remind me again" feature could be a field in the settings. For example `"IgnoreNewVersions":"2020-01-01,2020-02-01"` or `"IgnoreNewVersions":"all"`.

### Detecting new versions

New versions could be detected by downloading a specific file here on GitHub (using raw.githubusercontent.com). The properties file parser could be re-used for this.

For example, the URL `https://raw.githubusercontent.com/UltraStar-Deluxe/Play/release/version.properties` could point to a file containing current release information.

The version naming of USPlay might change (like "Windows Vista" is newer than "Windows NT"), so I suggest to use the release date to check for newer versions.

Example file:
```
version.name = UltraStar Play 1.2.3.4
version.release_date = 2020-06-02
download_link = github.com/blabla.zip
website_link = github.io/blog/USPlay-coolest-newest-version-get-it-now-get-it-Get-It-GET-IT
```

**Comment by basisbit** [comment]
USDX also has such a VERSION file at https://github.com/UltraStar-Deluxe/USDX/blob/master/VERSION
To check if there is a more recent version available, one could simply check if the content of the version file is not equal to the installed version.
