### ISSUE TITLE
Do not preview video types that are not supported

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/Play#150]
Issue type: Bug report

### Actual behaviour
On the preview screen:
* If a song has a video, but Unity [on the platform it's running] does not support that video type, the cover thumbnail thing becomes a black square
* There are no lines in the log related to videos on the preview screen

On the song screen:
* The background goes black for a split second, before falling back to a static background image (if any; I only tested this with songs that also had background images)
* Relevant log lines for the song screen:
```
[Player01] start (or continue) singing of スマイル at 0 ms.
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Writing database
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Start recording with 'WUP-021-0 Mono'
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Video file '/home/bbq/.ultrastardx/songs/Official/[JP][S2E18] Smile Smile Smile/video.mp4' does not exist. Showing background image instead.
```

### Expected behaviour
* If the preview screen cannot play the video, just fall back to the thumbnail (instead of a black square)
* Optionally: since at this point the game _knows_ it will not play the video, don't try it again on the song screen because of the extra flash.

### Steps to reproduce
Use an unsupported video format. In the example above, this was achieved by running a AVC-encoded video in an MPEG-4 container (aka, pretty much your standard .mp4) **on Linux**.

### Details
Provide some additional information:

- UltraStar Play version: Linux build from (I'm assuming) March 15, 2020 ~11:16
- Operating System + version: Archlinux
- Note that the actual log line is also a bit misleading, since (at least in this case) the video absolutely exists. If non-existing and unsupported formats cannot be distinguished, make the logged message more generic.
- Spaces (or strange characters) in path names are not the issue here, I tested it with something that has zero spaces or strange characters in the path, same result.

**Comment by barbeque-squared** [comment]
Can confirm that this is fixed. Very elegantly done, the user experience is much better this way.

**Comment by basisbit** [comment]
Thank you @barbeque-squared for confirming this!
