### ISSUE TITLE
How to identify songs (SongHash vs. Title+Artist)?

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#153]
### Problem or question to be solved

At the moment a hash of the song body (i.e. notes and lyrics) is used as key to identify songs and their highscore in the database.json.
This has considerable downsides, which I addressed in #152.

- The association between song and highscore should not change when fixing lyrics or modifying notes in the song editor. Thus hashing the body as song id is not a good solution.
- Similarly, I would not suggest to hash the full song header either. Changing for example #videogap or adding information (e.g. year) should not break association between song and highscore.
- Furthermore, the song hash made it difficult to see which entry is for which song when looking at the database.json.

### Suggested solution/s

As alternative, I suggest to use another SongMeta property to uniquely identify a song, namely **title** and **artist**.
- It is natural to identify songs by their name and artist, maybe year and album. This is how people talk about them. For ultrastar songs, title and artist are mandatory fields such that these are well suited to identify them.
- Title and artist should be sufficiently unique. Even if an artist has created different versions of the same song (e.g. an acoustic or live version), then this can and should be reflected in the title of the SongMeta (e.g. "The Sweet Song (live)").

- Instead of a hash, these fields can directly be concatenated to create an Id. This has the advantage that the id is still readable by humans when looking at the database.json. Why create a hash? To sum up a lot of data (such as the song body) this makes sense. However, if the identifying fields are short enough, then hashing them is more like an obfuscation to the human eye.

**Comment by sophof** [comment]
I would personally prefer to also be able to differentiate duets versions (and possibly other versions) that refer to the same song, without having to duplicate the song files and change the title. I think this suggestion would make that impossible.

A different solution to your issue could also be to just always move the existing highscore to the new hash. Of course, this'll only work if it the edit is done in-game.

**Comment by achimmihca** [comment]
> A different solution to your issue could also be to just always move the existing highscore to the new hash

Yes this should work.

I had a second thought on this and think you are right.
Having a unique hash enables correct online highscore comparison and matchmaking (e.g. for #68).

When I look at my Spotify library, then there are tons of songs with the same name by the same artist, e.g. from live concerts, remixes, covers of own songs, etc.
Title and artist might work for a small song library with some thousand files. But on massive scale it does not seem to be optimal.

I also thought about a URI as alternative identifier. But it only makes stuff more techie and difficult to use.
Actually, I do think that a URI should be a valid value for the #MP3 tag. But only to reference YouTube or Spotify songs (#87).
