### ISSUE TITLE
Toggle window/fullscreen mode via global shortcut

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#161]
Would be nice if one could toggle fullscreen / window mode via global shortcut (i.e. a shortcut that works in all scenes).

This requires a new common scene object, e.g. `GlobalShortcutKeyboardController`

To toggle fullscreen/window mode, I suggest `F11`, which is also used by performous and some browers (at least Firefox and Chrome)

**Comment by bohning** [comment]
Yes, good idea. An alternative would be ALT+ENTER (common in Windows, I believe), but I think F11 is more cross-platform and easier.

**Comment by achimmihca** [comment]
Alt+Enter is indeed a common shortcut to toggle full-screen. However, implementing it would be more difficult because of the interactions with other actions that are triggered via Enter key.
Such issues might be solved when switching to Unity's new input system.

Anyway, for now the only shortcut to toggle full-screen mode is F11.

**Comment by basisbit** [comment]
fixed by #163
