### ISSUE TITLE
Log and skip unknown file extensions

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/Play#166]
This idea came out of a discussion in PR #164. When scanning the song folder(s), files with unknown file extensions could be logged and skipped.

**Comment by achimmihca** [comment]
Note that this should be done for audio files as well as video files.
If a song uses an unsupported video format, it should be logged. This makes it easier to migrate a whole library of songs to a supported format.

**Comment by Baklap4** [comment]
I wouldn't rely on the extension as it can be faked and even wrong. Not sure if unity keeps track of this but i'd suggest reading the first few bytes, and check the file headers to determine if it's a file you can process or not

**Comment by bohning** [comment]
> I wouldn't rely on the extension as it can be faked and even wrong. Not sure if unity keeps track of this but i'd suggest reading the first few bytes, and check the file headers to determine if it's a file you can process or not

I would consider this extra credit. In a first version, considering file extensions and logging unsupported files would be of great benefit already (and pretty simple to implement, I suppose).

**Comment by achimmihca** [comment]
> I wouldn't rely on the extension as it can be faked and even wrong

I would not bother detecting such issues while scanning for songs. And I would not start implementing media decoding. Unity is the platform on which USPlay is built, so we should rely on their API and media support.
If Unity API has issues opening a file, then we should handle it as it occurs. But in-depth analysis of what might and might not work beforehand is wasted effort in my opinion.

**Comment by basisbit** [comment]
in general, the idea is to get much more people to just download/install usdx format tar/zip files and feed them to the game. Thus, people who create those song packages usually make sure that the content works. Especially on smartphones or tablets or TVs you'll not want to deal with file formats or adjusting song timing.
All in all this will hopefully improve the song files quality, get people to use modern + widely supported file formats (see [here](https://github.com/UltraStar-Deluxe/Play/wiki/Converting-Song-Media-Files), and make it much easier for occasional players to add their content to the game.
