### ISSUE TITLE
publish android app on f-droid as well

### ISSUE THREAD

**Issue by natrius** [UltraStar-Deluxe/Play#178]
As it is open source, do you plan to release it on F-Droid store as well? Its an open source store for android. https://f-droid.org/ You can use a special template so its easy to see directly in the app the last changes or the cahngeset of the last update. Should work automatically as well, afaik.

https://f-droid.org/

In the FAQ there is a short introduction as well https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

Ref: https://github.com/UltraStar-Deluxe/Play/issues/104

**Comment by achimmihca** [comment]
The apk is created by our docker build. A download link can be found on travis-ci. 

Just scroll down the last build log to finde a download link. 

* example link to build: https://travis-ci.org/github/UltraStar-Deluxe/Play/jobs/753797583
* click "view log" and scroll down
* the download link ends with UltraStarPlay-build.tar.gz or similar

I guess, someone can publish this apk on F-Droid.

**Comment by achimmihca** [comment]
Here is a PR of someone who added a project to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/2121/diffs
Looks like one has to provide a txt file with some data.
The example links to a gradle project on GitHub.

Question is, how to provide a link to an apk.
Or maybe even to a release containing an apk. Then a new GitHub release of USPlay might be available in F-Droid without further doing

**Comment by achimmihca** [comment]
UltraStar Play does not satisfy the [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy) of F-Droid:
```
For software to be FLOSS, the software in its entirety must be so - including all libraries and dependencies used.
Additionally, it must be buildable with only FLOSS tools.
```

UltraStar Play is built on Unity, which is a proprietary platform.
Thus, we cannot publish it to F-Droid

**Comment by natrius** [comment]
Thanks for looking into this. Maybe create your own repository so everybody can just include your repository into F-Droid? https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/ Just a thought :)

**Comment by natrius** [comment]
@achimmihca You could, as i said, create your own repository and make it autogenerate. It has the benefit of the people installing it through the f-droid repository getting autoupdate and that quite fast. You might be able to ask if @IzzySoft is able to take into his repository, but you have to match/use the fastlane file structure if I remember correct. 

Nice to see the project getting forward :)

**Comment by achimmihca** [comment]
As I said above, UltraStar Play does not satisfy the Inclusion Policy of F-Droid.

People are free to fork and modify UltraStar Play as they please and can try to create a release on F-Droid.

But given their policy, I think any attempt will be in vain because the Unity platform is not FOSS software.

However, a release on Google Play may be nice for Android users.

**Comment by IzzySoft** [comment]
While criteria for my repo are a bit less strict than F-Droids, it usually does not include games. I might consider an exception to that here, but then the file size of the APK is also beyond the 30M per-app limit set with my repo. A quick scan of the APK reveals:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Unity3d Ads (/com/unity3d/ads): Ads
* FMOD (/org/fmod): NonFreeDep

3 offenders.
```

which would be just inside the tolerated numbers.The missing Fastlane structure however would not be a stopper; though I'd highly recommend it (so you have control about how the app is presented), I'd just need a fine description, the icon, and ideally some screenshots. But category PLUS size not fitting somehow outrules it.

An open way would be, as @natrius suggested, to create your own repo. That might be easier than you expect, see [this article](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo) and its follow-up one in my blog. All ingredients are free.

**Comment by achimmihca** [comment]
I see, users can add custom repos to their F-Droid client? And we could use this to provide our own repo for UltraStar Play?

**Comment by achimmihca** [comment]
The apps can now be found on the Google Play store for easier installation:
- Main game: https://play.google.com/store/apps/details?id=com.ultrastar.UltraStarPlay
- Companion app: https://play.google.com/store/apps/details?id=com.ultrastar.UltraStarPlayCompanion

Others may also create a release on F-Droid.
