### ISSUE TITLE
Feature:  add touch device support + swipe-scrolling support

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/Play#184]
### Actual behaviour

Currently the game is not fully usable without keyboard&mouse. For  example:
- [x] Esc key is needed to close some screens. The back button from some smartphones can help with that, if it is assigned.
- [x] Scrolling through the songs list does not support finger features / swiping.
- [x] Some buttons are too small to hit on small screens with high DPI and high screen resolution.
- [x] Can't open the text search (-> input text box) without keyboard.

### Expected behaviour

Most features of the game should be usable on touch-input-only devices like smartphones, too. Song editor is probably the main exception which would probably require an entirely different / more basic UI to be usable on touch-only devices. For the song editor, it should maybe show a warning message when a device without mouse/keyboard input is detected (if possible).

**Comment by achimmihca** [comment]
**New input system**
I guess this should be implemented after moving to the new input system #100 .
The new input system has been released in a stable version in Unity 2020.

**Escape key**
> Esc key is needed to close some screens

I think it is not even implemented for every scene in the menus. Should make this more consistent

**UI**
The UI should convey the available controls.
Maybe show some icons what commands / gestures are available in a scene. Maybe as help overlay or small enough to be always visible (USDX had this).

![2020-09-28 20_43_45-F__Dev_tmp_USDX Screenshots_USDX - Menus_screenshot0001 jpg](https://user-images.githubusercontent.com/14967033/94473173-232c6400-01cc-11eb-9320-2f28fc0820ac.png)

**Song editor**
I agree that the controls for the editor are rather complex. Anyway, basic editing on mobile devices would be nice.
Things like "context menu on long-press", toolbars, slide-in menu could make actions available.
I think, the controls and in part UI for mobile and desktop will likely be different when both worlds provide an optimal user experience.

**Comment by achimmihca** [comment]
**Controller input**
We should not forget controller input for consoles (and PC).
Required control schemes to have something for every platform: keyboard and mouse, touch, controller.

**Consuming events**
One has to think about consuming events. For example, Ctrl+V should not enter the V letter to the search text, it should only trigger the paste action.

I did not yet take a look at the new input system. I hope Unity provides for such requirements. 

**Configuration**
What might be nice to have is a configurable control scheme that can be changed by the user (e.g. in a separate json file, similar to Visual Studio Code).
This is not required but when thinking about a new control scheme and input system, this could be a consideration.

**Comment by achimmihca** [comment]
IMO all these issues have been implemented in a basic version.

Of course, UX can be further improved. However, I would prefer a new issue to discuss such details.
Also, all UI related issues will probably be much easier to implement and iterate once Unity releases their new UIToolkit in a stable version.
