### ISSUE TITLE
Guidelines for Unity3d development

### ISSUE THREAD

**Issue by pawciut** [UltraStar-Deluxe/Play#19]
Guidelines for Unity3d development needed

In current code there are following entities:
- Views (unity3d scenes)
- Models 
Static classes of managers f.e "SettingsManager", enums, non static classes f.e GameSetting
- Controllers
c# scripts that are hooked up in scene to main canvas, they have mostly only OnGui with debug text
- ViewNavigator
c# script hooked up in scene to main canvas (buttons call methods from this class to navigate between scenes)
- skin (unity3d skin file)
I guess it should be use for GUI themes but I don't think it is is hooked up anywhere in game

Questions & problems:
- There are no prefabs for UI (for user to change game setting)
Prefab probably should contain label, input field, buttons(left/decrease,right/increase)
- How should this gameObject that allow player to change setting be connected to scripts.
- Should there be script for prefab (logic of setting specific setting in script for prefab)?
- Should logic for specific view be entirely in controller (set specific setting, get specific setting)?
- We could use some guidelines for "frontend" structure, in "UltraStar Play Development README" there are some guidelines according project structure, but no guideliness for View<=>Controller in Unity3d.
I'm no expert in this matter so I'm not sure which approach should be the right one in order to link Views,prefabs, scripts(controllers and models)

**Comment by basisbit** [comment]
sorry, wasn't able to get some help from experienced game developers on this.
So far, all the current code was done after watching a few unity3d tutorials and me applying concepts that I usually use in java applications. 
Yes, prefabs need to still be created. I guess, we create whatever we actually need, and add more once required.
Not sure what you mean with your second question, maybe gitter chat would be a good place to talk about this.
I have never seen editor script for creating prefabs being used. I guess we will only have few prefabs, and thus can just as well do it by hand? As usual, do what you think fits best.
I heard that PlayerSettings class from unity should be used for storing. Also, Unity 2018.3 will support nested prefabs which will make dealing with compound UI elements much easier, so we could wait for this before creating too much of the settings and other UI stuff. Or we could check what there is available in the unity assets store and how other games implement grouped and standardized UI elements.
Logic that is specific to this one view should be within that one ViewController. But any logic that is view independent should not be in there.
Regarding the guidelines, if you have collected some experience with Unity, please help creating this best practices document - maybe this could be added to the CONTRIBUTING.md file. I think true MVC or MV-VC does not go well with how Unity3D is done. We should still try to separate UI, UI logic, game logic and model. I am absolutely open for suggestions regarding this.

**Comment by pawciut** [comment]
I' ve done some testing and experimented with more logic in controllers. I have one concern about the static classes, they are often imposible to unit test.

**Comment by basisbit** [comment]
we should keep such static classes simple and to a minimum. For example the PlayerManager should only allow easy access (+encapsulate creation,..) to the players, but not do any other fancy stuff. Unit tests can then test all the stuff regarding players and so on. Integration tests can test the PlayerManager. I guess finding some mocking framework would help to simplify writing tests.

**Comment by pawciut** [comment]
I've implemented some tests with Moq library (in version that supports .NET 3.5), it works with unity test runner. I will provide link for the specific version of library that we can use when i get home.

**Comment by pawciut** [comment]
https://www.nuget.org/packages/Moq/4.2.1510.2205
In my branch I've added it in "Play/UltraStar Play/Assets/src/util/"

1. Download the nuget and extract to any folder
![image](https://user-images.githubusercontent.com/16131463/43605366-63b5cb20-9698-11e8-9f6a-1502ca3b1c29.png)

2. In Unity -> Import new asset
![image](https://user-images.githubusercontent.com/16131463/43605232-0b13f6ae-9698-11e8-8e3a-30e437f80ffd.png)

3. and Pick dll
![image](https://user-images.githubusercontent.com/16131463/43605328-3f49c89a-9698-11e8-9033-5ad2fac291a6.png)

**Comment by basisbit** [comment]
> Turns out you have to change in Build->Player Settings->Other Settings->Compatibility with .NET 2.0
(was .Net 2.0 Subset)

That would result in loosing compatibility with Android, XBox and PlayStation as targets. We should be able to also write tests that work for building these targets, so I guess we'll need some other solution

**Comment by pawciut** [comment]
Hmm according to [Android Player Settings](https://docs.unity3d.com/Manual/class-PlayerSettingsAndroid.html)
 it should work but it will affect the game size. I haven't tested it on android thou.

![image](https://user-images.githubusercontent.com/16131463/43634964-f2e7689c-970d-11e8-894b-c40539db5f8c.png)

**Comment by bitfactory-frank-bouwens** [comment]
I'll try to take a look at this soon (I'll test the smartphone platforms)
