### ISSUE TITLE
Video preview slightly larger than cover/song info box

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/Play#192]
### Actual behaviour
In the song selection scene, the video preview is slightly larger than the song cover/song info box below the cover/video preview.

### Expected behaviour
The video preview should have the same size/position as the song cover.

### Steps to reproduce
Go to song selection scene.
Select a song that has a video.
Compare the size/position of the cover and of the preview video.

### Details
Provide some additional information:

- UltraStar Play version: latest master
- Operating System + version: macOS Catalina 10.15.7, 
- if applicable, add a log file

Cover:
![image](https://user-images.githubusercontent.com/1497707/97871976-8eaaa980-1d15-11eb-82b4-ead40790d1f4.png)

Video preview:
![image](https://user-images.githubusercontent.com/1497707/97872043-abdf7800-1d15-11eb-85b2-9181e8a5a2b0.png)

**Comment by achimmihca** [comment]
depends on #231
