### ISSUE TITLE
Logging ?

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#207]
### Problem or question to be solved
The alpha project names "Logging" as a requirement (https://github.com/UltraStar-Deluxe/Play/projects).
What exactly is desired here?

So far, some logging is done via Unity's Debug.Log methods.
Also, something like this has to be used for logging that should be visible in the Unity Editor's console view

**Comment by basisbit** [comment]
When users encounter problems and report those, it usually is quite tedious and difficult to figure out what caused the problem. A Logfile usually makes it much easier to analyze and then solve the issue. Such a log file should include errors, scene changes, problems found when scanning songs, problems encountered when loading settings, status log lines for the main steps/parts of game initialization (so you know where to look if some critical error happens) and so on.
