### ISSUE TITLE
File watcher also for built game on standalone platform (Win,Mac,Linux)

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#209]
### Actual behaviour

Theming and I18N use a file watcher to automatically apply new values to the current theme.
At the moment this is only done when using the Unity Editor.

### Expected behaviour

The file watchers could just as well be used in a built game such that users can easily create themes on their own.

Some refactoring has to be done to separate the Unity Editor related code and the general file watcher code.

**Comment by basisbit** [comment]
Not all Unity targets support FileWatcher, thus that code has to be written so that those targets are still supported.

**Comment by achimmihca** [comment]
Closing for now.
Could be re-opened (or created newly) when the new (downloadable) theming using style sheets has been implemented.
