### ISSUE TITLE
Vertical bar to separate phrases in ScrollingNoteStreamDisplayer

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#210]
### Actual behaviour

Currently, when using the scrolling note stream, then it is hard to tell where one sentence ends and the next starts.

### Expected behaviour

One could show a vertical bar at the end of a sentence.
However, I am not sure if this is really needed. Is anyone missing this?

I saw such a thing on a Rockband screenshot: 
![Rockband-Singing](https://user-images.githubusercontent.com/14967033/100270381-453a2c80-2f58-11eb-8555-a6e1c5b6b48b.png)

**Comment by eldan-dex** [comment]
I never thought about it, but now that you mention it I think it would be a nice feature, I would certainly use it. Could also be made optional in case somebody would prefer the original style.

**Comment by MairusuPawa** [comment]
Hey! I think this indeed would be a nice feature to have, in that display mode. This brings another question though - how to handle it? The TXT files already have line breaks, but maybe they're not the best fit for the UI role, especially when it comes to lengthy instrumental parts in a song.
