### ISSUE TITLE
ScrollingNoteStream not properly rendered on Linux

### ISSUE THREAD

**Issue by paradigmn** [UltraStar-Deluxe/Play#211]
Issue type: Bug report

### Actual behaviour
Notes in ScrollingNoteStream mode aren't rendered (they are invisible). Additional "artifacts" are produced when hitting a correct pitch (ref. screenshot). 

### Expected behaviour
Notes should be visible and move from right to left as seen in issue#210.

### Steps to reproduce
Compile master branch of Ultrastar Play on Debian.

### Details
- UltraStar Play version: master branch 26.11.20, 
- Debian Bullseye
- Screenshot:
![Screenshot_20201126_132455](https://user-images.githubusercontent.com/18099075/100352288-102be980-2fed-11eb-9c85-05b97c5cd511.png)

**Comment by achimmihca** [comment]
Ahh yes, the notes do not move to the left because Update was called only once.
Will be fixed alongside #206

Kudos for singing perfect without seeing anything ;)
