### ISSUE TITLE
Musical score notation for notes

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#213]
**Motivation**
I found that there is interested in displaying notes using musical notation:

- https://github.com/performous/performous/issues/516#issuecomment-675864009

I think it is a natural development for people who are interested (or start to be intersted) in music to be confronted with music notation at some point.

I think UltraStar is a great tool to playfully learn basic singing skills. Having an option to display notes in music notation could be helpful for the enthusiastic.

**Goals**

- The goal is to provide an option to display notes differently
    - could also be done in addition to the normal note displayer

You can find on wikipedia a list of musical notation symbols: https://en.m.wikipedia.org/wiki/List_of_musical_symbols

What should be feasible
- Show "G clef" and lines
- Show sixteenth eighth, quarter, half, and whole notes (maybe with dots) on a line with correct accidental

Optional:
- Show break symbol if there is a clear break ?
- Show beamed notes ?
- Show 4/4 or 3/4 time signature ?

**Non-Goals**

- The goal is not to support full music notation. This would be way too complex.
- The goal is not to extend the song file format, pitch detection, or game play.

**Implementation**

Which note-symbol to use:
- Timing of notes is defined by the BPM of the song file.
    - However, this is note necessarily the same as a quarter note in the song.
- Thus, I would add a new tag to the song file that defines how many of the BPM-beats are actually needed for one whole note (or for one quarter note?).
    - Using this value, it can be calculated for a BPM-note if it is a quarter note, half note, etc.
    - I suggest to round this broadly (if there is one BPM-beat missing to a quarter note, then it should still be displayed as a quarter note)

How many quarter notes are in a bar:
- This information is needed to show vertical line to separate bars
    - Could be defined in an additional tag in the song file

Which line to use:
- Either use absolute pitch of note and draw it using corresponding ledger lines
- or use mapped pitch to the always same octave.
    - For UltraStar's scoring the octave is irrelevant
    - But this might be too much simplified to provide meaningful music notation ?

**Comment by timgoeller** [comment]
This might be interesting: https://www.smufl.org/fonts/

**Comment by achimmihca** [comment]
I don't think the required work would be worth it. Getting this right would be pretty hard. Doing something half-hearted would be of little use.

I think the number of users interested in such a feature is close to zero.
IMO we should focus on other aspects of the game.

Thus, won't fix.
