### ISSUE TITLE
Option to select voice for player in duets

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#239]
### Actual behaviour

UltraStar Play assigns the first voice to the first player (in list of PlayerProfiles I think) and the second voice to the second player.

### Expected behaviour

The user should be able to choose who sings which part.
When singing a duet with only one player, then there should also be a third option to merge the voices (there is already a merge implementation).

- Any UI ideas for this feature?
    - Accepting the default order should require only a single additional submit-Action (e.g. Enter)
- To differentiate the voices in the UI
    - their lyrics have to be shown to the user
    - the song file can contain `#P1` and `#P2` to name the singers

**Comment by bohning** [comment]
In UltraStar, the voice assignment is toggled via pressing Space.

**Comment by basisbit** [comment]
@bohning from a UI perspective however that is rather bad and not intuitive design. I have seen people accidentally switch them while searching and each time have them be different, so they did not know who is where.
USP is not a rewrite of USDX, but instead is a new sing-along karaoke game which supports the usdx file format - the rest can be different.
