### ISSUE TITLE
Custom player profile images

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#240]
### Actual behaviour

Users can choose from a predefined set of player profile images.

### Expected behaviour

It should be possible to add custom images.

This could include: 

- Taking an image with a webcam
- Having a special folder location in which images are searched
    - For example `Application.persistentDataPath + "/PlayerProfileImages"`
- The PlayerProfile should then save the absolute path to the image location.
- If a previously used image is not found anymore, then it should fall back to a default player profile image.

**Comment by basisbit** [comment]
I am not sure if it is desirable to have player icons for profiles. Their main purpose is to show players where on the sing screen "their" notes are. Besides that, it would be nice to get rid of them and simplify the UI, especially for the mobile device targets. Any ideas for alternative solutions?

**Comment by achimmihca** [comment]
> Their main purpose is to show players where on the sing screen "their" notes are

And a custom image would improve this. The player profile image is also shown on the SingingResultsScene.

Also I think this is a good purpose, at least if there is enough space. Otherwise only the player name is left. But "reading" an image is often faster than reading text.

In the current SingScene UI, the player image does not take additional space because the row is used anyway to show points and the player name.

But I also understand that on a small display or with lots of players, the image could be hidden. It is redundant with the player name after all. However, this deserves another issue IMO. After the migration to UIToolkit.

**Comment by achimmihca** [comment]
Maybe adding custom profile images is not needed.
But I would like to offer more choice in the default profile images.

I noticed that other big platforms (e.g. Netflix) offer cartoon animals as profile image.
This looks fun, is distinguishable, and one can associate oneself with certain characteristics of the animal (big, strong, cute, etc.)

Maybe there is a cartoon style set of images under liberal license that we can re-use?

There are also some nice silhouettes of people and animals on [publicdomainvectors](https://publicdomainvectors.org/en/search/profile%20image).
Someone could create profile images for USPlay from these.
