### ISSUE TITLE
Jukebox feature

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#242]
There is not yet a "jukebox" feature in UltraStar Play.
UltraStar Deluxe has this. It's like a small media player for your song library.

UltraStar Play could support this as well.

For the implementation, a new Scene would make sense.
- The video and audio player can be taken from the SingScene.
- What is missing then is only a song list and some controls to play/pause, etc.
    - For inspiration, look at USDX and UltraStar World Party

This should be implemented directly with Unity's new UIToolkit.

**Comment by jimmyhawkin** [comment]
Vocalux does this brilliant and would be a good example on how to do it.  Were if people hear a song they like and wanna sing they can get right on it.

**Comment by achimmihca** [comment]
>  Were if people hear a song they like and wanna sing they can get right on it.

This has been requested recently with #405
