### ISSUE TITLE
Party modes

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#243]
UltraStar Play does not yet support party modes.

I took a look at UltraStar Deluxe for the basics: N teams play R rounds, each round with different game modifiers.

### Teams
- N teams
    - Each team with M players
- In each round, one player is chosen per team

### Rounds
- Song selection
    - in each round a random song is chosen out of a predefined set of songs
        - predefined sets of songs are: all songs, playlist, folder, etc.
    - every team has N joker
        - a joker can be used to selected a different song for this round (again randomly)

### Modifiers
Some party modes modify the game by hiding some elements. These are pretty simple to implement:
- hide notes
- hide lyrics
- mute audio (after a few seconds)

Then there are different "win" conditions:
- Reach N points
    - Normally the song has 10000 points. In this mode, the first team to reach N points (e.g. 5000) wins this round
- Reach an *advance* of N points
    - Your team needs for example 1000 points more than the other teams to win this round
- Hold your advance over N phrases

And there are other modifications to the normal game
- short song
    - start somewhere in the middle (where there are lyrics) and over a short duration (e.g. 1 minute)
    - this could maybe make use of the medley-start / medley-end tags in a song file
- pass the mic in your team every N seconds
    - the UI shows a "Next Player: YOURNAME" label and a loading bar to announce the change
- duell
    - even when there are more than 2 teams, only 2 of them are chosen this round

### Implementation
USDX named some combinations of above modifiers (e.g. "Blind 5000", "Hardcore"). Then users choose for each round one of these named configurations.

Instead, I suggest to
- Show controls for each modifier (e.g. a checkbox for "hide lyrics")
- Win condition could be a dropdown
    - options of the win condition should show up dynamically
- For each round, a slot is displayed
    - The current modifier configuration can be assigned to a slot
    - Configuration can be copied to other slots via drag and drop
- Optionally, users can name a configuration and store it as a preset.
    - This would allow fast loading of configurations, similar to what USDX did
    - Assigning such a preset configuration to a round-slot could be done via drag and drop
- A "choose random configuration" button could also be displayed
    - Thereby, some constraints might be useful. For example, the modifiers should be chosen randomly, but never mute the audio.

I think this is a better approach because
- it allows for more fine-grained control
- better explains what modifiers do
    - in contrast, to know what "Hardcore" does, you have to read the description

Note that these modifiers could just as well be available for the normal game, not only for party mode.

For some controls, I suggested drag'n'drop but when designing the UI, one also has to keep controller and keyboard input in mind. How these should work probably depends on the concrete UI.

Do you have more ideas for fun modifiers in party modes?
What do other games offer (Vocaluxe, SingStar, Rockband, Performous, etc.)?

**Comment by bohning** [comment]
What I really liked with regard to party modes was the possibility to "cheat" when both singers agreed to not sing a computer-proposed song, not using a veto/joker. I think "1" used a joker for team 1, "2" for team 2, and holding ALT while pressing either proposed a new song without using a joker.

**Comment by achimmihca** [comment]
Actually, I wonder if the jokers are needed. I would also allow this option always.
Why sing a song that you don't want to sing?

**Comment by bohning** [comment]
Well, I guess that’s a matter of taste. For me, it is one reason for the party modes - that you sometimes have to sing a sing that you wouldn’t normally, depending on how many jokers there are left. That’s part of the fun. However, as described above, when both players don’t want to sing the proposed song or don’t even know it, they can skip the proposed song without sacrificing a joker.

**Comment by daggeg** [comment]
> Actually, I wonder if the jokers are needed. I would also allow this option always.
> Why sing a song that you don't want to sing?

If your on your own that makes sense. But if you sing with friends and family it's not that easy. I seldom want to sing the same songs as my kids or (some of) my friends. Even my wife and I don't get along as to which songs to sing sometimes . To me the challenge loses its' nerve without jokers, its' USP. But with jokers you get bring a strategic element to the mix which makes it so much more fun when competing .

**Comment by basisbit** [comment]
Afaik, touch UI / mobile devices is still the main target of UltraStar Play, so just doing this over keyboard presses won't work when people use a tablet + screen sharing to play the game on their TV (or they use an android TV or similar which supports android apps)

**Comment by jean-moreno** [comment]
Hello, I've started a branch with work on the Party Mode.
You can read an overview of the current design/flow in this commit: https://github.com/UltraStar-Deluxe/Play/commit/458404afb0325c640800d4755e30e5f1c67db87d

Additional notes:

Game Modifier design: a game modifier has one or multiple actions, and is triggered by one trigger condition.
Possible Actions:
- Hide Notes
- Hide Score
- Hide Lyrics
- Lower Audio Volume (to 10%), I thought that an entirely silent audio could be disorienting for non experienced players, and the idea is to hear singers way more than the audio. The actual target volume could be an option though.
Triggers:
- Always
- When Time is Reached
- Until Time is Reached
- Within Time Range
- When Score is Reached
- Until Score is Reached
- Within Score Range

For the score-based triggers, there is an option to trigger the action only for the player who has fulfilled this score condition, for actions that are relevant to the player (hide notes, hide score).
For example:
Hide notes when a score of 2000 is reached => notes for each players will be hidden when they reach 2000 points.
If that option is disabled, the notes will be hidden whenever *a* player reaches 2000 points.

Time-based triggers are in percentage of the total song duration.

More notes:
- The system has been designed to support multiple game modifiers per round, however the UI will only allow one
  - Multiple modifiers could allow progressive obstacles for leading players, e.g. hide score after 2000 points, hide notes after 6000 points, etc.
- The "Teams" mode doesn't work at all, it will mostly be a lot of UI work to nicely present things
- The "Free for All" mode only works with exactly two microphones enabled

In its current state, in the "Free for All" mode, you should be able to add a number of users, and have them play against each other successively with randomly chosen songs (or not).

**Comment by achimmihca** [comment]
Another win condition could be a "last one standing", i.e., after a certain percentage of the song, the player with lowest points is out.
This is a common game mode for racing games.

The opposite would also be possible: after a certain percentage of the song, the player with highest points claims the current best place while the others continue to sing for the remaining places.

A possible downside of this approach is that players are finished earlier, which can be frustating or boring.

**Comment by achimmihca** [comment]
I implemeted the UI for party mode configuration:

![party-mode-config](https://user-images.githubusercontent.com/14967033/212635951-02c08fea-ff93-4d62-9386-9ab763311a55.gif)

I think it covers all requirements from this issue.

I want to include these party modes in the upcoming Steam release.
For now, I did the implementation in a private repository.

**Comment by achimmihca** [comment]
I was thinking about the party mode, what is it really about?

In the first planned implementation

- modifiers to the normal game play have been proposed.
    - I still think This is a fun idea.
    - However, these modifiers are not necessarily related to the party mode.
    - In my current implementation, I allow to set these for the regular game as well.
- multiple rounds can be played
    - Again, this is not necessarily related to the party mode.
    - In my current implementation, one can also queue next songs, players, and modifiers for the regular game.
        - This has the advantage that it is not necessary to plan and configure all rounds and their modifiers upfront. Just focus on the current round you want to play.

So, what is left in the "party mode" is 
- teams
    - each round, one of the players of a team is chosen (round robin)
    - I think this is a good feature for larger groups
- team scores
    - after each round, the team with highest score receives 2 points, the second team 1 point
    - after the final round, there is a screen that shows team results (gold, silver, bronze medal for first three teams)
- knock-out tournament
    - after each round, the team with lowest score is out and cannot participate in following rounds.
    - I think this is a good feature for competitive players
- free-for-all as alternatives to teams
    - this is implemented simply as "everyone is his / her own team"

Looking at these features, I think it makes sense to
- rename the "party mode", for example to "team & tournament"
- remove the upfront configuration of modifiers
    - only set the number of rounds to play

Modifiers and configuration of multiple rounds can work the same way in the normal game, which harmonizes the features. This might event reduce complexity.
