### ISSUE TITLE
Player id and microphone webcam scanner

### ISSUE THREAD

**Issue by ZePhyr1987** [UltraStar-Deluxe/Play#245]
Issue type: Feature request

I would pay a bounty for this wish. :)

Requirement:
- Player already created.
- Webcam / barcode scanner.
- Each microphone receives a barcode / QR
- Each player receives a barcode / QR
(Card, bracelet or similar)

Behavior:
- Before each round, the player can scan himself and the selected microphone.

- A barcode / QR to remove unused microphones would also be nice. ^^

That would make bigger parties extremely easy.

**Comment by achimmihca** [comment]
From your description, I assume that you want to achieve a fast change of players at bigger events?
A barcode does not strike me as the optimal solution here...

Instead, I suggest to extends the Companion App with features such as
- adding player profiles
- selecting songs, players, and their mic for the next round

On the main game side, this would require something like a song-queue.
I think Vocaluxe has a similar "Smartphone control" feature.

Would this be a practicable solution for you?

**Comment by ZePhyr1987** [comment]
Everything that makes party management easier is welcome.
At the moment I am overwhelmed by song wishes and player changes after every song.
If the player change took place in the background without my intervention, it would be very pleasant.

**Comment by achimmihca** [comment]
Closed in favor of #176.
If you have more ideas for an API (and stuff that can be controlled via Companion App) that would make party management easier, then feel free to add these ideas there.
