### ISSUE TITLE
Audio Stops Working in Android After One Song

### ISSUE THREAD

**Issue by maeblythe** [UltraStar-Deluxe/Play#250]
Issue type: Bug report

### Actual behaviour
After completing a song on the latest Android build, the audio cuts out completely and does not come back until the app is restarted.

### Expected behaviour
The audio should not stop working completely.

### Steps to reproduce
1) Open UltaStar Play Android app
2) Play through a single song

### Details
Provide some additional information:

- UltraStar Play version: 0.3.1
- Operating System + version: Android 11

**Comment by achimmihca** [comment]
I cannot reproduce this on my Galaxy S10e with Android 11.
Please attach the log file to this thread. Log file location is described [here](https://github.com/UltraStar-Deluxe/Play/wiki/Logging-(Serilog)).

Which device do you use?
If this is a device specitic issue, then a new Unity version might fix it.

**Comment by maeblythe** [comment]
Sorry for wasting your time! My phone (moto g power) was probably just glitching out previously. Right now, I am also unable to reproduce the issue.
