### ISSUE TITLE
Slides for multi-note syllables

### ISSUE THREAD

**Issue by lukthy** [UltraStar-Deluxe/Play#253]
### Actual behaviour

When a syllable goes across 2 or more notes ("~"), the drawn notes are not connected.

### Expected behaviour

Since the space between the notes is actually sung, they could be connected by a "slide note", like the ones they use on Rockband.

![image](https://user-images.githubusercontent.com/11531364/135946131-d004f39d-9574-476e-b544-bb38c3937926.png)

### Details

This will not work properly with the current note positioning implementation, since some notes can be truncated into the wrong position relative to other ones, and the "slide notes" could make players think they have to change the pitch in the wrong direction.

**Comment by lukthy** [comment]
I think they should be shown only for display, so I'd choose case 2.

I've seen songs with no room between notes, even some SingStar ones, so they could be drawn only when there is enough space. Maybe a time-based space? like 50ms?

As for the pitch, I think a linear interpolation would be too strict on some long slides. I've done some tests, and I believe Rockband allows any pitch between the two connected notes to be considered as correct.

About the note positioning, I still have to check how other games deal with songs with a wide range of notes. I think Rockband has markers in the songs to change the current range of notes, but that is not feasible for all the UltraStar songs that already exist.

**Comment by achimmihca** [comment]
I want to note that I will not implement this.

- I see little to no benefit for the game play
- It requires quite some work
    - One would have to implement a new way to draw notes that supports lines in arbitrary angles
    - Note positioning is unclear
        - Scoring requires working note positioning to decide what counts as "any pitch between the two connected notes". Currently, octaves are wrapped such that there is not really a "in between" notes.

However, I encourage others to implement it if they have an idea how it can be done.

**Comment by basisbit** [comment]
"in between notes" are any notes. They can go up or down, notes are not bound to an octave. You'd want to give points if the previous and following directly "touching" pitches are within the "correct" margin.

**Comment by achimmihca** [comment]
Will not implement
