### ISSUE TITLE
Game stuck when opening song

### ISSUE THREAD

**Issue by sfetzel** [UltraStar-Deluxe/Play#261]
Issue type: Bug report

### Actual behaviour
The game freezes when starting the song from the txt file "Toploader - Dancing In The Moonlight.txt" (from http://usdb.animux.de)

### Expected behaviour
The game singing activity should start.

### Steps to reproduce
0. Add song with mp3 to songs folder (txt file attached)
1. Open the ultrastarplay
2. Click on "sing"
3. Select Toploader - Dancing in the moonlight
4. Game freezes

### Details
- UltraStar Play version: 0.3.1
- Debian GNU/Linux buster
The reason seems to be line number 8 in the file "Toploader - Dancing In The Moonlight - game crashes.txt" attached to this issue. When I delete this line, the song starts just fine.

[Toploader - Dancing In The Moonlight - game crashes.txt](https://github.com/UltraStar-Deluxe/Play/files/7500274/Toploader.-.Dancing.In.The.Moonlight.-.game.crashes.txt)

**Comment by achimmihca** [comment]
Confirmed, the error message is
```
VoicesBuilderException: Error at line 8: Linebreak encountered without preceding notes
VoicesBuilder.ThrowLineError (System.UInt32 lineNumber, System.String message) (at Assets/Common/Model/Song/Builder/VoicesBuilder.cs:235)
```

We should probably make the VoicesBuilder less strict and accept such minor issues.
For example, the following should trigger the same error because there are two sentence endings without notes between:
```
#ARTIST:Toploader
#TITLE:Dancing In The Moonlight
#MP3:Toploader - Dancing In The Moonlight.mp3
: 228 4 72 We 
: 236 2 72 get 
: 240 4 75 it 
: 248 2 67 on
: 252 5 65 ~ 
: 260 2 63 most 
: 264 2 65 ev
: 268 2 63 'ry 
: 272 3 65 night 
- 280 296
- 297 298
: 300 2 63 when 
```

A superfluous sentence end can be ignored and logged with a warning.

**Comment by achimmihca** [comment]
@sfetzel Please re-test with the Linux build from [here](https://github.com/UltraStar-Deluxe/Play/actions/runs/1445604932)

**Comment by bohning** [comment]
I also sometimes see a line break before the final E (which unfortunately leads to a crash in UltraStar Manager). This should probably also simply be ignored and logged to Error.log.

**Comment by dan-r95** [comment]
I dont think I can download a build, or at least I dont see a button

**Comment by achimmihca** [comment]
There is not a dedicated button. You have to click the "Build" text of "Artifacts".

For me, this is a download link (one archive with all target platforms). But when I log out then it is not a link, just text.
As I said, I am unsure if others can download the artifact.

--
<img width="1278" alt="2021-12-06 20_57_10-github" src="https://user-images.githubusercontent.com/14967033/144914200-e7d14567-b833-4063-af36-971c1875a75d.png">
-

**Comment by achimmihca** [comment]
This is the download link: https://github.com/UltraStar-Deluxe/Play/suites/4317071756/artifacts/112883183
It works for me when logged in. Is it working for you?

**Comment by dan-r95** [comment]
Yes, thank you!
