### ISSUE TITLE
Can't open the song editor

### ISSUE THREAD

**Issue by Rom888** [UltraStar-Deluxe/Play#266]
Issue type: Bug report

### Actual behaviour

Nothing happens when I press E on the keyboard from the Song Select screen.

### Expected behaviour
"You can open the editor from the Song Select Scene and from the Sing Scene by pressing E on your keyboard."

### Details

- UltraStar Play version: 0.3.1
- Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by achimmihca** [comment]
This has been changed to Ctrl+E. The docs are not up to date. 
You can also try right click context menu on a song cover. 

Reason is that by now, typing a character will jump to songs with matching name.

**Comment by achimmihca** [comment]
I updated the wiki
