### ISSUE TITLE
Song editor: pressing the play/pause button resets position

### ISSUE THREAD

**Issue by Rom888** [UltraStar-Deluxe/Play#267]
Issue type: Bug report

Actual behaviour
Pressing the play/pause button resets the position to zero.

Expected behaviour
Pressing the play/pause button keeps the current position.

Details
UltraStar Play version: 0.3.1
Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by achimmihca** [comment]
That's a feature. When ending play mode, the cursor jumps back to where it has been started.

This should behavior should be switchable, e.g. via toolbar button.

**Comment by achimmihca** [comment]
Not sure if I implemented this already, but holding ctrl or shift or alt might prevent the jump back.

**Comment by Rom888** [comment]
> That's a feature. When ending play mode, the cursor jumps back to where it has been started.
Okay, I think it makes sense.
