### ISSUE TITLE
[Mac] Play can’t find songs that have a typographer’s apostrophe in it

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/Play#276]
Issue type: Bug report

I try to use the typographer’s apostrophe (’) instead of the typewriter’s apostrophe (https://en.wikipedia.org/wiki/Apostrophe#Typographic_form) in my filename. I added a task to UltraStar Manager that can replace all wrong uses (accents:  `´) and typewriter’s apostrophes by the (more correct) typographer’s apostrophe. The typographer’s apostrophe is also included in Windows CP1252, so even old UltraStar (before 1.1, also CMD) can handle this character.

When I start Play with my song collection I noticed that about 20 % are missing when compared to USDX and after a while I noticed that all the songs with apostrophe’s in their filenames are missing. The problem with the apostrophe also becomes evident when starting songs that have apostrophes in their lyrics (basically all English songs):

![image](https://user-images.githubusercontent.com/1497707/152934884-db286098-22f2-4150-926e-2293418cf648.png)

So somehow the typographer’s apostrophe cannot be decoded and is displayed as "???". So then I started play with only one song that had a typographer’s apostrophe in its filenames - and indeed, Play says "No songs found".

Looking into the log file, I find:

![image](https://user-images.githubusercontent.com/1497707/152935042-8adff3fb-5fba-4e88-9a4d-d231bc003217.png)

Meanwhile, USDX does not have a problem with the file at all, so the filenames referenced in the text file and the filenames themselves are indeed identical (and must be, otherwise USDX would complain as well).

![image](https://user-images.githubusercontent.com/1497707/152935174-96adfc4b-4916-42f8-a394-be442c51faa3.png)

This is where it gets strange: the same file works on Windows without problems (tested by @achimmihca).

### Steps to reproduce
Start Play with a song that has a typographer’s apostrophe in the filenames.

### Details
Provide some additional information:

- UltraStar Play version: latest master
- Operating System + version: macOS 12.1 Monterey
- if applicable, add a log file

Relevant lines from the log are:

```
2022-02-06 21:29:41.271 [WRN] Audio file does not exist: /Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi???s Song.mp3
2022-02-06 21:29:41.271 [INF] Finished song-scan-thread after 22 ms. Loaded 0 songs. Failed 1 songs.
```

Does anybody have an idea what’s going wrong?

**Comment by achimmihca** [comment]
Did you try other encodings? UTF8 should work in all cases.

However you could try UTF8 with/without BOM and utf16 (BE and LE).
Does it change anything?

**Comment by bohning** [comment]
Good point. The current encoding of the text file is UTF-8. I will test other encodings as suggested and report back.

**Comment by bohning** [comment]
So now I created several copies of the song’s text file and saved them with the following encodings:

- CP1252
- UTF8 w/o BOM
- UTF8 w BOM
- UTF16 LE w/o BOM
- UTF16 LE w BOM
- UTF16 BE w/o BOM
- UTF16 BE w BOM

As expected, USDX finds three versions: CP1252, UTF8 w and w/o BOM.

Interestingly enough, Play finds two versions: UTF8 w BOM and UTF16-LE w BOM.

The relevant lines from the log are:

```
2022-02-09 21:56:35.882 [WRN] Audio file does not exist: /Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi?s Song.mp3
2022-02-09 21:56:35.918 [WRN] SongMetaBuilderException: /Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi’s Song_UTF8-UTF16-BE-noBOM.txt
/Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi’s Song_UTF8-UTF16-BE-noBOM.txt does not look like a song file; ignoring
2022-02-09 21:56:35.925 [WRN] SongMetaBuilderException: /Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi’s Song_UTF8-UTF16-LE-noBOM.txt
Required tag 'artist' was not set in file: /Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi’s Song_UTF8-UTF16-LE-noBOM.txt
2022-02-09 21:56:35.926 [WRN] Audio file does not exist: /Volumes/Karaoke/++/SongsHomeGrown/Beatsteaks - Mietzi’s Song [MB&HR]/Beatsteaks - Mietzi???s Song.mp3
2022-02-09 21:56:35.927 [INF] Finished song-scan-thread after 111 ms. Loaded 3 songs. Failed 4 songs.
```
