### ISSUE TITLE
Switch to .NET 4.x

### ISSUE THREAD

**Issue by nikolaosginos** [UltraStar-Deluxe/Play#28]
I would propose targeting .NET 4.x for this project to be able to use the Task Parallel Library for easier threading implementation the usage of newer C# language features.

I have already done this in my local clone. I could submit a pull request.

Was there any specific reason for staying with 3.5 or was this just the default setting?

**Comment by basisbit** [comment]
we are using unity 2018.1.4f1, which still has some known issues with .Net 4.x. If you get unity to compile this project and run tests on travis-ci or a docker container, we'll gladly upgrade to 2018.2.x

**Comment by basisbit** [comment]
with current versions of Unity properly supporting .Net 4.x and travis-ci now using a version that also supports .net 4, there should be no reason left not to switch now. @nikolaosginos this was your suggestion, thus could you please create the pull request for this change?

**Comment by nikolaosginos** [comment]
> with current versions of Unity properly supporting .Net 4.x and travis-ci now using a version that also supports .net 4, there should be no reason left not to switch now. @nikolaosginos this was your suggestion, thus could you please create the pull request for this change?

Yes, I will take care of this
