### ISSUE TITLE
Code Style: remove redundant type in instantiation (`Bla bla = new Bla()` vs. `Bla bla = new()`)

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#283]
### Problem or question to be solved
We once decided against type inference using `var` keyword because we wanted to specify the **resulting** type explicitly.
Thus, we currently use the redundant form `Bla bla = new Bla()` instead `var bla = new Bla()`.
This is especially noisy with generics, e.g. `Dictionary<string, string> string2string = new Dictionary<string, string>();`

### Suggested solution/s
However, newer C# versions allow to skip the redundant constructor type.
Thus, one could write `Bla bla = new()`.
Note that the resulting type is still explicitly specified.

### Your opinion on the topic
I think this is a smart c# feature.
It removes the redundant type specification but on the right-hand-side, such that the resulting type is still clear for the reader.

Thus, I argue that we should use this. My IDE has a nice "code cleaup" feature, that can apply this to whole code base.
Any other opinions ( @basisbit ) ?

**Comment by basisbit** [comment]
Personally, I suggest sticking to what majority of potential devs are familiar with, what tends to survive lots of iterations of refactoring, and what is easy to read even for new devs.
Imho `Bla bla = new()` probably does fulfill these requirements. I assume the compiler or IDE by default warns the user if there is already a `new()` function in local context?

**Comment by achimmihca** [comment]
> `Bla bla = new()` probably does fulfill these requirements

It does. 

But I also argue that smart language features such as these can improve the code base.

For example, the long form for getter properties also does fullfill these requirements.
But the short form is even easier to read:
```
public Bla BlaProperty { get { return blaField; } };
vs.
public Bla BlaProperty => blaField;
```
At first, I was tending to the long form, because I felt the short form might be less readable if you do not know the feature.
But after I got used to it, I must say that I prefer the short form now because it reflects the simple relationship between property and backing field (and it is much shorter when each { and } would be on a separate line).

> sticking to what majority of potential devs are familiar with

So yes, it depends on what people are familiar with.
But on the other hand, becoming familar might be the better approach.

> what is easy to read even for new devs

What is easy to read is what "majority of potential devs are familiar with".
I don't know what average C# dev knows.

Otherwise same as before: "becoming familar might be the better approach"

> what tends to survive lots of iterations of refactoring

Here, I see the advantage at the short form, because it has less redundancy.
For example, change of type would be one change instead of two.
Note that this is also true for change of generic type (Java uses "diamond operator", e.g. `new ArrayList<>()`)

Overall, I think the short form would be beneficial without the drawback of the `var` keyword (i.e. accidental change of type).

> I assume the compiler or IDE by default warns the user if there is already a new() function in local context?

I dont understand.
There is no warning from the compiler when using the short `new()` form.
On the other side, my IDE suggests to use the short form.

**Comment by achimmihca** [comment]
If we decide to use the new feature, then now would be a good time because there are large refactorings anyway (#284).

**Comment by achimmihca** [comment]
Let's compare:
```
List<MicProfile> mics = new List<MicProfile>();
```
I read this as: "Needed is a list of MicProfiles. Create it as a list of MicProfiles."

```
List<MicProfile> mics = new();
```
I read this as: "Needed is a list of MicProfiles. Create it."

Given how common this is, I think this little cognitive shortcut is actually helpful.
Other way around: it makes the case more obvious, where something more specialized is instantiated. For example:

```
List<MicProfile> mics = new CustomMicProfileList();
```
I read this as: "Needed is a list of MicProfiles. Create it as a specialized CustomMicProfileList"

Overall, I am convinced that C# offers something useful here. I really appreciate the C# approach.
It is less redundant than Java's diamon operator, which only skips the generic type (e.g. `ArrayList<MicProfile> mics = new ArrayList<>();`)
I like this also more than Python, which skips the `new` keyword, but still requires the class name (e.g. `bla: Bla = Bla()`)
And as I said, it does not have the drawback of type inference using `var` keyword.

So, I am sold ;)

**Comment by achimmihca** [comment]
> Imho `Bla bla = new()` probably does fulfill these requirements

...
......
😅 

Somehow, I read the long form `Bla bla = new Bla()`. My bad, it was late yesterday...
