### ISSUE TITLE
Note.EndBeat should be inclusive

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#295]
### Problem or question to be solved
Recently I ran into an issue because I expected Note.EndBeat to be inclusive but it is not.

Example: Note starting on beat 1 with length 1.
Currently, this results in:
- StartBeat: 1
- Length: 1
- EndBeat: 2

But what I expected is:
- StartBeat: 1
- Length: 1
- EndBeat: 1

Well, clearly I was aware of this at some time because the game works correctly (score etc). But now I find it very weird.
It could be that there are bugs somewhere (song editor) because of this pecularity.

### Suggested solution/s
I would like to refactor the value and usage of EndBeat to be inclusive.

### Your opinion on the topic
Is there any reason why EndBeat should not be inclusive?

Note that the semantic of the txt file is not affected. The EndBeat is only part of the internal data structure.

**Comment by basisbit** [comment]
A beat in UltraStar is a timespan, not a point in time. Thus, if you want to treat it like a point in time, always choose the beginning of the beat timespan. 
Thus:
- StartBeat: beginning of beat span 1
- Length: timespan of amounts of beats: 1
- EndBeat: beginning of beat span 2

Hope this helps understand the idea of it.

**Comment by achimmihca** [comment]
I think in this case it works as intended.
I added a doc comment that StartBeat is inclusive whereas EndBeat is exclusive.
Works for me, so will close this now.
