### ISSUE TITLE
Add background music

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#296]
### Actual behaviour

No music is playing in the menu.
Feels a little bit sad.

### Expected behaviour

Some background music should play when in the menu. This is common behavior in games and USDX has it as well.
Of course, the background music should not play in the song select, sing scene, and song editor.
The background music in the menu can be turned off in the settings.

I suggest to reuse the background music from USDX.
Or is there any other background music that we could use?

**Comment by basisbit** [comment]
The background music from USDX definitely should be good for a start. Might be worth it to look at what vocaluxe or performous are using. If you want it to be extra fancy, generating generic background music on the fly could be cool, too.

Depending on what music is used and its license, it might be necessary to display the artist name.
