### ISSUE TITLE
Controller/AndroidTV support 

### ISSUE THREAD

**Issue by Goltergaul** [UltraStar-Deluxe/Play#303]
Issue type: Feature request

### Actual behaviour

I tried running version 0.4.0 on my nvidia shield android tv. The menu can be controlled to some degree with a game controller, but it's rather frustrating/buggy. Would be cool to see support for game controllers at some point. On the other hand i also had a bit of performance problems running it on the shield but overall it seemed to work.

### Expected behaviour

Game controller support

Cheers

**Comment by achimmihca** [comment]
Controller support should already work in general, i. e., you should be able to do the same stuff with a gamepad that can be done with a keyboard. 

Which controller do you use for your AndroidTV? Does the issue also occur when using a keyboard (mabye a bluetooth keyboard for Android)?

**Comment by Goltergaul** [comment]
I use a Bitdo pro 2. I'll try with the newest version and get back to you and reopen this with more detailed information .

**Comment by Goltergaul** [comment]
Hi, i'm using an 8bitdo pro 2. I had some issues with not being able to do
some things. I'll try again with the newest version and collect some more
detailed info for you

Am Fr., 20. Mai 2022 um 13:09 Uhr schrieb achimmihca <
***@***.***>:
