### ISSUE TITLE
Reduce number of sentence ratings

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#304]
### Actual behaviour
The sentence ratings are not very distinctive.
Can you tell what is better: great, cool, good ?
Can you tell what is worse: awful, poor, bad ? 

Currently, there are 8 sentence ratings. These are in order: perfect (95%), cool (80%), great (70%), good (60%), notBad (50%), bad (30%), poor (20%), awful (0%)

IMHO this is too much and not distinctive. Thus, it does not provide a good feedback to the user.
This also affects the colors for the different ratings, which feel like 50 shades of green at the moment.

The ratings are also pretty harsh in their wording with "bad", "poor", and "awful". I don't think this is a good game design choice from a psychological perspective.

### Expected behaviour
I suggest to reduce the number of ratings to 5: perfect (95%), great (75%), good (50%), ok (30%), bad (0%)
IMO 5 ratings is a managable number. For some reason, most e-shops use 5 stars for reviews.

And as you see, there is only 1 "unfriendly" rating left. "bad" becomes "ok". "poor" and "aweful" are replaced with "bad".

Are there other opinions? Any arguments against this change?

**Comment by bohning** [comment]
I fully agree that 8 ratings is too much.

Regarding the percentages, I would make it somewhat symmetric: 100-95 %, <95-75 %, <75-50 %, <50-25 %, <25 %-0%

For these five ratings, my suggestions would be something like: excellent! (ausgezeichnet!), great! (großartig!), cool! (cool!), you can do better! (das geht besser!/das kannst du besser!), try harder! (streng dich an!).

Maybe native speakers can support here with "hip" wordings =)

**Comment by achimmihca** [comment]
Which words do similar games use for feedback?
For example, I know a game (Project Diva) which uses "cool", "good", "safe", "bad", "awful" (you lose some energy below "safe").

I agree with the 25% "symmetric" ratings.

But I would stay with "perfect" for the best score. I is intended for 100% (which would be perfect) with a little tolerance.

I think "excellent" is a pretty long word. Would prefer something shorter.
I think "great" and "cool" are not very distinctive (which one is better?). In contrast, I think people in general agree that "great" is better than "good"
I like "try harder" or similar. It is encouraging instead of only negative. But when using both "try harder" and "you can do better" then I'd say (again) it is not very distinctive.

Thus, I suggest 95% "perfect", 75% "great", 50% "good", 25% "ok", 25 %-0% "something"
where "something" is not positive but also not judging too much. For example,
- try harder
- unlucky
- not enough
- unhappy, sad (emotional)
- weak
- bummer
- oops (implying a mistake that was not necessary/by accident, in German something like "ups", "hoppla")
- ouch (implying some form of hurt / stress, in German something like "autsch", "uff")

IMO
- "try harder" and similar could be pushy and does not fit the other adjective ratings.
- the emotional stuff also does not fit the adjective ratings.
- the onomatopoeia (dt. "Lautmalerei", you know the "comic words" oops, ouch, uff) are not very clear.

Overall, I vote for "weak". It is not necessarily bad, but it is not good either, like in "could be better". And it is an adjective like the others.
Otherwise, I also think "bad" is clear and not too harsh as well. It is used in other games and fits pretty well.
