### ISSUE TITLE
Please make the install process for the Ultrastar Play Companion App for iOS install on both Mac and Windows pc's

### ISSUE THREAD

**Issue by XvisionedX** [UltraStar-Deluxe/Play#311]
Issue type: Development discussion

![Screenshot (3)](https://user-images.githubusercontent.com/107327265/173220890-b3c2bcc2-54cc-4a3d-aa35-61b3ae278c66.png)

### Problem or question to be solved

please make a clear STEP - By - STEP guide for install for ios on windows and upload to youtube.
Describe the issue to be discussed.

So i have tried following the process specified in the unity build and run from source code section, but when opening Unity project and switching to ios as soon as i try to build and run i get several error messages reffering to missing .git folder's and files missing commithash

### Suggested solution/s
Suggest some solutions or answers.

### Your opinion on the topic
What is your personal opinion?
Great program overall, but please improve the install of companion app. Check out Apples Test Flight programme - you can upload apps for beta testing - this will allow users to install via beta invite provided on the official github for the companion app.

**Comment by achimmihca** [comment]
I agree, we need a Mac / iOS dev to improve the support.

Anyway, the error message is because the commit hash is read from filesystem as part of the build to have a unique version number. Did you checkout the project using git?

**Comment by XvisionedX** [comment]
I see, yeah so, I’ve tried to do It a number or ways, from git bash the play-master to downloading and unzipping aye. I’m sure I’m missing something so silly 🤦🏻‍♂️ Spent about 5 hours tryna figure it out aye
________________________________

**Comment by achimmihca** [comment]
That's a good point, the build won't work when downloading the source code as zip.

Maybe it would be better to only show a  warning for the missing commit hash but do not fail the build.

**Comment by XvisionedX** [comment]
That’s good to know that way won’t work then ahaha.

I have been trying to compile through bitrise, not having too much luck there either aye, any suggestions? I’m windows only unfortunately aye
________________________________

**Comment by achimmihca** [comment]
Building for iOS requires a Mac and XCode.

It is not possible to build the final executable for iOS on Windows.

See our wiki: https://github.com/UltraStar-Deluxe/Play/wiki/iOS-Executable-Compilation

and Unity docs: https://docs.unity3d.com/Manual/UnityCloudBuildiOS.html

**Comment by XvisionedX** [comment]
You're a legend, thank you for your help aye.

Saved me a few extra wasted hours aye 😂👌🏼
________________________________

**Comment by achimmihca** [comment]
There is a built app file available for iOS in the 0.5.0 release.

Sadly, installation on iPhone is not as easy as it is on Android.
You could try to search StackOverflow for a solution: https://stackoverflow.com/questions/14535392/how-to-install-an-ipa-app-file-into-iphone-with-command-line/33547254#33547254

At some point, I wish to have USPlay on the Apple App store. But this is future work for now.
Until then, install is fiddly and requires a mac.

**Comment by XvisionedX** [comment]
Of course, have you considered doing a Apple test flight beta? It’s a good way to get your apps on to the official AppStore as you get real reviews, bug reporting from users. A controlled amount of people able to join the beta program allowing you to hand out beta invites to people genuinely struggling with the install aye.

The website Bitrise allows you to build iOS apps from repository’s. Are you familiar with this method at all?

Or do you potentially have any advice on the build companion app .yml file that’s in the actions section?
________________________________

**Comment by XvisionedX** [comment]
Yo!! You are not going to believe it 😂🤦🏻‍♂️ So it is ridiculously easy on windows you just need the 0.50 iOS.zip. And a program called sideloadly.

I'm more than happy to create a tutorial for you to put on the main Git hub page if you'd like my friend. You've been more than helpful to me it's the least I could do!
________________________________

**Comment by achimmihca** [comment]
Great! You can update the [wiki page on download and install](https://github.com/UltraStar-Deluxe/Play/wiki/Download-and-Install). 

Add a section "Installation - iOS" for other iPhone users. Thanks!

**Comment by achimmihca** [comment]
I updated the wiki
