### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by TheNormMan** [UltraStar-Deluxe/Play#312]
Hey,

I have Version 0.5.0 Commit 0b25639 on Windows
At some songs the letters ß,ä,ü,ö disappear, but not in all Songs.
Even the songs (where it happens) are no Problem for UltraStar Deluxe.

Here 2 Songs where these letters disappear:
[Annett Louisan - Das Spiel.txt](https://github.com/UltraStar-Deluxe/Play/files/8919902/Annett.Louisan.-.Das.Spiel.txt)
[Cro - Traum.txt](https://github.com/UltraStar-Deluxe/Play/files/8919909/Cro.-.Traum.txt)

And here one where everything is fine:
[Cro - Bye Bye (MTV unplugged).txt](https://github.com/UltraStar-Deluxe/Play/files/8919911/Cro.-.Bye.Bye.MTV.unplugged.txt)

hope thats enough information, have no clue what could be helpful in addition to that

**Comment by achimmihca** [comment]
That's probably an issue with file encoding.
USPlay does not try to guess file encodings like USDX did because this approach had other issues (see #276).

Please, encode the files as UTF-8 and try again.

**Comment by achimmihca** [comment]
relates to #376
