### ISSUE TITLE
Issues with Linux paths

### ISSUE THREAD

**Issue by MairusuPawa** [UltraStar-Deluxe/Play#313]
Issue type: Bug report

![image](https://user-images.githubusercontent.com/1774599/174502555-0c3104dc-470e-4b9f-91d7-c3f1261acfdf.png)

### Actual behaviour
When typing (or pasting) a valid path into the "Song Library" settings, the game claims that "the file does not exist". The default path for downloaded song, for some reason, does not display this behavior.

Additionally, the backspace key does not work in the input field.

### Expected behaviour
Ultrastar Play should find the given path and load the songs.

### Steps to reproduce
1. Deploy Ultrastar Play in for isntance /opt/ultrastarplay/ and run "StandaloneLinux64"
2. Go to Settings → Songs
3. Enter or paste a valid path to your local song library
4. Warning message will be shown immediately

### Details
- UltraStar Play version: [v0.5.0](https://github.com/UltraStar-Deluxe/Play/releases/tag/v0.5.0)
- Operating System + version: Ubuntu 22.04

**Comment by achimmihca** [comment]
Did you try to remove the trailing slash?

File permissions are ok?

The path is checked with plain C# API which should work.

**Comment by achimmihca** [comment]
Note that shell specific shortcuts will not work, e. g. ~ for the home directory

**Comment by achimmihca** [comment]
This is a bug. I made a mistake when replacing backslash and slash (was needed to work around stupid Unity TextField behavior).

This issue affects all platforms except Windows.
Will fix it soon

**Comment by achimmihca** [comment]
Should be fixed with https://github.com/UltraStar-Deluxe/Play/commit/311b2f5192963a9724d20ce66d2007cdce2bee5b
