### ISSUE TITLE
File browser for song folders

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#315]
### Actual behaviour

One has to copy and paste the path to song a folder. 

### Expected behaviour

A dialog opens to select paths. 
Has the advantage that available paths can be viewed. 

Might work better with external storage (sd card) on Android. 

There are already MIT licensed solutions:
- https://github.com/yasirkula/UnitySimpleFileBrowser
- https://github.com/yasirkula/UnityNativeFilePicker

Should give it a try.

**Comment by achimmihca** [comment]
UnityNativeFilePicker is pretty neat.
It works on Windows.
But
- it cannot select a folder, only files
- on Android, it always shows some path in a "cache" folder.

 Thus, I won't add it.

I also have other issues with SD card on Android.
I don't think UnitySimpleFileBrowser will help with this.

**Comment by achimmihca** [comment]
Won't fix

**Comment by alagane** [comment]
For now is it possible to use external USB storage to get songs from? I have my songs on a USB key and I would like to be able to use them if I plug the USB on my Android device.

**Comment by achimmihca** [comment]
> For now is it possible to use external USB storage to get songs from?

Good question, I did not test this yet. I can check this soon.
I'd say it depends on Android, whether it allows file system access for UltraStar Play (probably not by default)

**Comment by achimmihca** [comment]
Nope does not work. I updated my comment above.
