### ISSUE TITLE
UTF-8 support on song names

### ISSUE THREAD

**Issue by eray-kurtulus** [UltraStar-Deluxe/Play#318]
Issue type: Bug report

### Actual behaviour
The game does not display songs with non-English (or non-ASCII) characters on their names.

### Expected behaviour
The game should display songs with non-English (or non-ASCII) characters on their names. UltraStar Deluxe Worldparty plays these songs without any problems.

### Steps to reproduce
1. Download the song "Mor ve Ötesi - Cambaz" from [https://ultrastar-es.org/en/canciones?artista=Mor%20Ve%20%C3%96tesi](url)
2. Copy it to the songs path (default is %APPDATA%\LocalLow\Karaoke\UltraStar Play\Songs)
3. Open the game (I opened it through StandaloneWindows64.exe)
4. Search through the songs list, you will not see the newly added song.

Alternatively, you can probably rename an existing song. I haven't tested this. I have had this problem on multiple songs with UTF-8 characters.

### Details
- UltraStar Play version: v0.6.0
- Operating System + version: Windows 11 21H2 Build 22000.795
- Log file, related section screenshot:
![ultrastar_play_log_ss](https://user-images.githubusercontent.com/8824676/179246372-4b3dc234-74df-4205-97a0-a021a8d4dd15.jpeg)

- Full log file:
[UltraStar Play20220708.log](https://github.com/UltraStar-Deluxe/Play/files/9121748/UltraStar.Play20220708.log)

**Comment by achimmihca** [comment]
The paths to the media files (avi, jpg, png, mp4, etc.) are defined in the song txt file.
Save the song txt file as UTF-8 and it should work.

The log shows messed up characters, because they were read this way from non UTF-8 song txt file.

**Comment by achimmihca** [comment]
USPlay by default assumes UTF-8. This differs from other UltraStar games.
See also #276, #312.

**Comment by eray-kurtulus** [comment]
Thank you for the quick help! I had just downloaded the project to collaborate on this issue. Seems like there were no problem at all.

I failed to properly paste the URL, it links to a github page, but it works if you copy-paste it instead of clicking on it :')

**Comment by achimmihca** [comment]
relates to #376
