### ISSUE TITLE
Folder view in song selection menu

### ISSUE THREAD

**Issue by aratar-orome** [UltraStar-Deluxe/Play#321]
Hello,

thank you for your great work. The look and feel of UltraStarPlay is awesome. 

I feature request is about add an option to change the view in the song selection menu. The reason for that is, I and probably also other people have a very big song database and organized there songs in folders. I would be great to see this folders also in the song selection menu to keep the overview. 

Thank you very much,

Andreas

**Comment by achimmihca** [comment]
You can already sort by path.

One could also easily make the path a searchable property.

Is grouping the songs by some property (path, language, etc.) really needed? Or is sorting and searching by path enough?

> to see this folders also in the song selection

If you really want to group by some property, where do you want to see the grouping?
Please, make sure that your solution would also work to group by other song properties.

**Comment by aratar-orome** [comment]
Thank you for the hint regarding the possibility to sort by path. Unfortunately, sorting is only done by the drive letter. E.g. "C" if songs are located in the drive c:\. 

To be honest I would prefer a more file explorer look. At least in Vocaluxe you are able to change the view to a folder view. 

I want to explain my main use case for that:
I have e.g. 4000 songs and for a party I want to update my song database and created 30 new songs. I just need a possibility to display only this new songs and not the other. What is the best way to do that if I don't have a folder grouping?

Nevertheless, sorting by creation date would be also helpful.

An additional grouping function would be great. You could add this just below the sort function button. There you could be able to select the group criteria, may be the same like in the sorting function. And then in the song selection view appears a folder for each group. E.g. when you have selected grouping by "year" then e.g. three folders appear "1999", "2010, "2022". Then you can select a folder, so that only songs are visible that satisfy the grouping criteria e.g. "2010".

**Comment by achimmihca** [comment]
> sorting is only done by the drive letter

the drive letter is part of the full path, but it should not be the only part considered for sorting.

When you sort by path and your 30 new songs are in a common subfolder (e. g. "my new songs") then you should be able to find the songs next to each other.

---
You could also create a playlist for the songs and filter by that.

---
To filter by a specific song property, you can already enable this as search property and search, e. g. for year "2010".

I dont think grouping would help with that

---
A folder view would be different. This would be like a file browser for songs, with multiple levels of nesting, etc.
I think this would be a better solution than grouping for large song libs.

I will think about it

**Comment by aratar-orome** [comment]
Thanks for your helpful answers. I am happy that you are thinking about file Browser Support, but I think there could be more important Features to implement. 😅

**Comment by achimmihca** [comment]
This has been implemented in the private repo for the Steam release of Melody Mania.
Currently only in the beta branch.

**Comment by aratar-orome** [comment]
Great news. I have bought Melody Mania on Steam already. 😁
