### ISSUE TITLE
Lyrics are cropped on Android (Google Pixel 6)

### ISSUE THREAD

**Issue by jonadem** [UltraStar-Deluxe/Play#324]
Issue type: Bug report

### Actual behaviour
Lyrics in "bubbles" are cropped on a Google Pixel 6 phone (Android) even with only one player

![Screenshot_20220902-234902](https://user-images.githubusercontent.com/5641556/188240908-59e4d9da-8178-4ec7-8184-34b7f70c2bb4.png)

### Expected behaviour
See the full height of the lyrics in the bubbles when only one player is selected

### Details
Provide some additional information:

- UltraStar Play version: v0.7.0
- Operating System + version: Android 13

**Comment by achimmihca** [comment]
Yes, this needs a dynamic font size calculation.
Workaround: disable lyrics on notes in the settings.

Similarly, a very long name of a song is cut off in song select scene. This also needs a dynamic font size.

Unity's UIToolkit does not yet have a "fit text in parent as large as possible" option, but it should be possible to calculate the font size using [TextElement.MeasureTextSize](https://docs.unity3d.com/ScriptReference/UIElements.TextElement.MeasureTextSize.html)
