### ISSUE TITLE
Add support for Singstar usb converter microphones for PS2 PS3 (on android)

### ISSUE THREAD

**Issue by Daviddevits** [UltraStar-Deluxe/Play#328]
Hi, on Ultrastar Deluxe its possible to use the usb converter (a 2 channel usb analog to digital audio converter) and assign a channel to player1 and player2. Is this possible/ can this be made possible on Play?
Android sends it to the Android audio input and i can selec tthat in the recording menu but i do not see a way to split channels to 2 players

**Comment by achimmihca** [comment]
unfortunately, Unity does not support recording from different channels of the same device.
It's a limitation of their API.

See also our [FAQ](https://github.com/UltraStar-Deluxe/Play/wiki/Frequently-Asked-Questions-(FAQ)#how-to-assign-different-channels-of-a-recording-device-to-different-players)

**Comment by achimmihca** [comment]
duplicate of #85
