### ISSUE TITLE
Hide notes ("Note Display Mode: None")

### ISSUE THREAD

**Issue by byt4** [UltraStar-Deluxe/Play#332]
My friends and I especially love about Ultrastar Play that it has a "no score" option, so we can sing alone or together without competition. However, with the notes always being displayed, some apparently still feel forced to sing "correctly" rather than just having fun.

Therefore, I'd like to request an additional option to hide the notes (e.g. "Design Options" -> "Note Display Mode: None").

That way, it would be possible to enjoy Ultrastar Play like in a Japanese karaoke bar or like using karaoke software such as Joysound Karaoke Wii U. :)

**Comment by achimmihca** [comment]
This would be easy to implement.
But why not just watch the music video on ,e.g., Youtube then instead?

There also was the idea to hide nodes as one of the party modes ( #243 ). But this was intended to sing "blindly", i.e, beeing rated without seeing the notes.

With separate options to hide notes and disable scores, players will be able to do this, so they can choose how they want to play.
Thus, I think it is a good idea to implement this.

**Comment by byt4** [comment]
> This would be easy to implement.

I hoped so. :)

> But why not just watch the music video on ,e.g., Youtube then instead?

Simple: I think that during a party, Ultrastar is a lot more convenient than using YouTube.

> Then they can choose how they want to play. Thus, I think it is a good idea to implement this.

That would be great!
