### ISSUE TITLE
Path with plus character not working for audio / video / image files

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#339]
### Actual behaviour
When using an image, audio, or video with a plus character, then this file cannot be loaded.

From the log file:
```
2022-11-21 21:34:12.989 [ERR] Error loading Texture2D from: file://C:/Users/andre/AppData/LocalLow/Karaoke/UltraStar Play/Songs/songs-master/Creative Commons/Dead Smiling Pirates - I/cover+.jpg
```

### Expected behaviour
The files should work, a plus character is a valid character for a file name.

### Details
Media files are loaded asynchronously using Unity API.
The method used to load the file from local file system is the same that is used to load it from a web server via HTTP.
Thus, I think the plus character may need to be URL encoded (see [StackOverflow](https://stackoverflow.com/questions/5450190/how-to-encode-the-plus-symbol-in-a-url)).

Other characters should also be checked. Maybe the path need to be URL encoded in general.

The txt files are not affected, because these are loaded with different C# API.

- UltraStar Play version: v0.8.0
- Operating System + version: Windows

**Comment by manureini** [comment]
Hello ;)

I'm facing the same issue when I use a network share for my songs.

Error loading Texture2D from: file://\\192.168.2.121\public\Sonstiges\Ultrastar Lieder\2 Unlimited - No Limits\2 Unlimited - No Limits[CO].jpg
Malformed URL
Error loading Texture2D from: file://\\192.168.2.121\public\Sonstiges\Ultrastar Lieder\257ers - Holz\257ers - Holz[CO].jpg
Malformed URL
Error loading Texture2D from: file://\\192.168.2.121\public\Sonstiges\Ultrastar Lieder\2be3 - Donne\2be3 - Donne [CO].jpg
Malformed URL

maybe you can try to encode the url if not already done
https://learn.microsoft.com/de-de/dotnet/api/system.web.httputility.urlencode?view=net-7.0

regards Manuel
