### ISSUE TITLE
Companion App not compatible 

### ISSUE THREAD

**Issue by S1llycat** [UltraStar-Deluxe/Play#343]
Hi, I just came across USP yesterday (been a DX user for several years). I followed all the steps but the companion app is showing a not matching version (main game 4 and companion 3). I saw that the newest version of the game was just released 8 days ago so I downloaded the older version but that didn't help either. Anything else I can do? 

Issue type: Bug report

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should actually happen

### Steps to reproduce
Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Open the ultrastarplay.exe
2. Click on button X, then on the menu that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Details
Provide some additional information:

- UltraStar Play version:
- Operating System + version
- if applicable, add a log file

**Comment by achimmihca** [comment]
Please use the companion app that is released alongside the main game: https://github.com/UltraStar-Deluxe/Play/releases

There once was a dedicated repository for the companion app. This old companion app version will not work anymore.
Maybe we should delete this old companion app repo?

**Comment by S1llycat** [comment]
It worked! Thank you so much!
Yes I think there is an old link somewhere that I used..
