### ISSUE TITLE
Support for AAC / M4A / MP4

### ISSUE THREAD

**Issue by Rumbah2** [UltraStar-Deluxe/Play#344]
Issue type: Feature request
It would be great if Ultrastar Play supported AAC music. It is usually in a mp4 container named .mp4, .m4a or .aac .

### Actual behaviour

I get it listed in song errors with unsopported audio format ( in either .mp4, .aac, m4a)

### Expected behaviour

It would be great if this format was supported (ffmpeg can decode it)

**Comment by achimmihca** [comment]
There is a roadmap of Unity for audio/video: https://unity.com/roadmap/unity-platform/audio-video
A planned feature is "Runtime Decoding":

> The Unity media framework exposes all the building blocks needed to make various workflows such as low-level decoding, encoding, playback, recording, etc. This first implementation phase of the framework will let users leverage raw audio/video decoding for situations where custom content needs to be ingested at runtime (e.g.: custom feeds from devices, data from proprietary file formats, etc).
> We’re aiming to expose availability of the H.264 video decoder and AAC audio decoder on all platforms. Developers would also be able to add their own implementation of these decoders if they wish to go beyond the capabilities of the stock implementations.

This should enable mp4 support on all platforms.
My only doubt is that Unity tends to need decades to go from "planned" to "released" for a feature... 

See also #280

**Comment by bohning** [comment]
That would indeed be a great improvement.

**Comment by achimmihca** [comment]
mp4 already works on some platforms already including Windows and Android.

**Comment by basisbit** [comment]
(I am also on Windows 11 and AAC audio + h264 video in mp4 container works without any problem here in UltraStar Play on m machine.)

**Comment by Rumbah2** [comment]
I don't have audio and video in one file, an example:
`#TITLE:I Want You
#ARTIST:Savage Garden
#LANGUAGE:Englisch
#EDITION:SingStar '90s
#GENRE:Pop
#YEAR:1996
#MP3:Savage Garden - I Want You.m4a
#COVER:Savage Garden - I Want You [CO].jpg
#BACKGROUND:Savage Garden - I Want You [BG].jpg
#VIDEO:Savage Garden - I Want You [VD#0].mkv
#VIDEOGAP:0
#BPM:212,4
#GAP:21963,28`

**Comment by Rumbah2** [comment]
Sorry, misclicked and closed it

**Comment by achimmihca** [comment]
The thing is that Unity supports some audio codecs only in the context of an mp4 file.
For example, an mp4 with aac / m4a as audio may work as video file (relates to #272). But the aac / m4a audio alone may not work.
Plus, the supported formats are platform dependent.

For better file support, a third party lib (e.g. ffmpeg) could be integrated.
However, this is out of scope for now.

**Comment by achimmihca** [comment]
Will be implemented with #362
