### ISSUE TITLE
Support for special characters / UTF-8

### ISSUE THREAD

**Issue by byt4** [UltraStar-Deluxe/Play#349]
The latest version (v0.8.0 on Windows) neither opens files nor displays lyrics containing characters such as French "é" and German "ä".
This hasn't been any problem in earlier versions.

I suppose that this has to do with some setting for character encoding/decoding.

Thank you and keep up your great work!

**Comment by achimmihca** [comment]
The default encoding was changed at some point to UTF-8. Guessing of encodings has been dropped because it was causing issues in some cases.

Please ensure that your file is encoded in UTF-8 and try again. It should work.

**Comment by basisbit** [comment]
byt4 Is the problem about the encoding of the content of the .txt files or about the filename (of the .txt files)?

**Comment by byt4** [comment]
@achimmihca and @basisbit, thank you for your replies!

I didn't know that the guessing of encodings had been dropped. Indeed, now it only works if the content of the .txt files is encoded in UTF-8.

I'll have to batch convert all these .txt files then...

**Comment by achimmihca** [comment]
> I'll have to batch convert all these .txt files then...

If you found a good tool for this, please let me know.
Last time I checked, I did not find anything that was (a) easy to use and (b) working well enough.

**Comment by achimmihca** [comment]
relates to #376
