### ISSUE TITLE
Visual Bug in Singing View

### ISSUE THREAD

**Issue by LoaderB0T** [UltraStar-Deluxe/Play#352]
Issue type: Bug report

### Actual behaviour
When singing a song with two microphones, the second pitch indicator does not seem to work correctly. It seems the highlights boxes all have the minimal width (at least after the first few pixels of each line). Actually, the very first line in the video example below also shows the issue for player one!

This issue ONLY happens when both players are singing. As soon as player one does not sing, the boxes for player two work as expected. So I suspect some sort of simultaneous rendering issue or something. Also, the lyric indicator at the bottom only works for a small section of each line.

Based on the score calculation I conclude that this is not an issue with the audio input, as both players have similar scores.

See this video for an example:

https://user-images.githubusercontent.com/37637338/209969110-63d00b03-3e69-4b28-a1a9-b4658686bee5.mp4

### Expected behaviour

The pitch indicator should render correctly for any number of players & the lyric indicator should not stop after a short section of each line.

### Steps to reproduce

For me, this just happens with every song, no special trick, I think.
Happens with both pitch analysis algorithms (which makes sense since I think this is a mere presentation error).

### Details

- UltraStar Play version: 0.8.0 (386f749f)
- Windows 11 22H2

**Comment by achimmihca** [comment]
Thanks for the detailed bug report.
Your description is on point. Looks like the notes are recorded correctly but visually their width is not updated.

> Also, the lyric indicator at the bottom only works for a small section of each line.

I can confirm both issues in v0.8.0

However, I cannot reproduce the issue anymore in current master version.
So I assume this will be fixed with the next release.

**Comment by LoaderB0T** [comment]
Hi there, thanks for the quick response!

I just tested with the latest build and can confirm this is fixed for me as well. Thanks!
