### ISSUE TITLE
Resolution to a higher value not possible

### ISSUE THREAD

**Issue by supernevi** [UltraStar-Deluxe/Play#353]
Issue type: Bug report

### Actual behaviour
I'm using windows 10 and UPlay V 0.8.0.
It is not possible to set the resolution to a higher value -> the right arrow button doesn't seem to work.

### Steps to reproduce

1. Open the ultrastarplay.exe
2. Click Settings
3. Click Graphics
4. Try to click the right button for the resolution -> doesn't work
5. For more 'fun' click the left button and then the right button -> it works
6. For a lot of more fun, click the left button twice and try to double click the right button -> works only once (as if I had clicked only once)

No information in log files.

Happy new year :)

**Comment by achimmihca** [comment]
Confirmed. The right button to change resolution seems to be broken at times.

**Comment by supernevi** [comment]
ok forget it. i compiled and started again with current master. here it seems to be everything fine. 
so i close this issue
