### ISSUE TITLE
UltraStar on Raspberry Pi (aka. RasPi, RPi)

### ISSUE THREAD

**Issue by Tirgatt** [UltraStar-Deluxe/Play#356]
I was trying to get UltraStar to work on a Raspberry Pi 4 (8GB).

I started by trying to run UltraStar Play on Raspbian with the help of Box64. A window also opens very briefly, but it collapses immediately.

The second attempt looked more promising: I used a snap from UltraStar Worldparty on Raspbian for this. Unfortunately, UltraStar Worldparty hung up very quickly and 4K videos lagged hard, even though the Raspberry Pi is advertised with 4K support. I suspect that this is not necessarily due to the Raspberry Pi, but to the software, since even my high-end gaming laptop UltraStar Deluxe could not play 4K videos smoothly - but UltraStar Play had no problems.

On my last attempt I installed LineageOS from KonstaKANG on the Raspberry Pi and installed the Android version of UltraStar Play. The problem here is that hardware video decoding is not supported. Accordingly, the videos cannot be played back. Or I don't know how to get it work.

I'm pretty sure UltraStar will run on the Raspberry Pi. Maybe not with a super performance, but acceptable.

So I would be very happy to see a version of UltraStar Play optimized for the Raspberry Pi. (preferably as an ISO file)

**Comment by achimmihca** [comment]
> The problem here is that hardware video decoding is not supported.

You could try webm/vp8 encoded video files. These have best cross platform support in Unity.
I think Unity will fallback to software rendering for webm/vp8 if needed.

**Comment by Tirgatt** [comment]
Works for me. Nice, thank you!
