### ISSUE TITLE
Sing all duet lyrics with single player

### ISSUE THREAD

**Issue by Tirgatt** [UltraStar-Deluxe/Play#363]
Unfortunately, songs that are offered as a duet cannot be sung alone. In order to be able to sing it alone, you would need to edit the TXT file and have it in both a duet version and a solo singing version.

Wouldn't it make sense if UltraStar Play offered a "P1+P2" choice in addition to just "P1" and just "P2"?

Of course there are songs where you can't sing both players at the same time, but then the notes are on top of each other, which UltraStar Play should recognize, right?

I think this approach works better when "P1+P2" is set as the default, since a song downloaded as a duet won't suddenly be missing lyrics.

**Comment by Tirgatt** [comment]
For me it's (a) ;)

**Comment by achimmihca** [comment]
The following has been implemented for the Steam release:

- option to sing both vocals of a duet song
    - Thereby, all phrases of the first vocals are included
    - phrases of the second vocals are included only if they do not overlay with an existing phrase

This allows to sing a merged version of duet songs without overlap.

**Comment by Tirgatt** [comment]
For me, a duet is always an upgrade for a song/txt file. When you need to provide two TXT files and Ultrastar also shows two different songs in the UI, it will be confusing for the user. "Which one should I use?" It also bloats the search results. Instead of skipping the song once, you have to skip every version of it.

With two TXT files you also double the possibilities where the user has to choose how many players to sing the song with. You have the option in the interface and the second version of the song/TXT file. From my point of view it should be in one place.

**Comment by achimmihca** [comment]
Your argumentation is on point. I created a dedicated issue (#418) for this.
