### ISSUE TITLE
Song editor scrolls the wrong way.

### ISSUE THREAD

**Issue by Tirgatt** [UltraStar-Deluxe/Play#364]
Issue type: Bug report

### Actual behaviour
If you open the song editor on a song, mark notes by holding down your left mouse button and then get to the lower border of the window to mark notes that are behind that border, the editor scrolls up instead of down.

### Expected behaviour
If you hit the border while marking notes in the song editor it should scroll in the direction you are marking.

### Steps to reproduce
Open UltraStar Play, choose a Song to edit, mark some notes in the editor by holding your left mouse button and move the cursor to the lower (or upper) corner.

### Details
Provide some additional information:

- UltraStar Play version: 0.8.1 Commit: 5d2c4396
- Operating System + version: Windows 11 Pro 22H2

![Animation](https://user-images.githubusercontent.com/1659982/211352258-69c39633-2450-47d8-a899-e96814840498.gif)

**Comment by achimmihca** [comment]
Yeah, will try to make a new release soon with fixes for the song editor.

The song editor should also not be affected by user defined themes (buttons should not be blue).

**Comment by Tirgatt** [comment]
Even if you use the scroll wheel: In the Editor it scrolls in the opposite direction as in the song selection.
