### ISSUE TITLE
Scene change animation broken in built game

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#373]
### Actual behaviour
No scene change animation is visible.

### Expected behaviour
There should be a smooth transition from one scene to the next.

### Steps to reproduce
The issue occurs only in the built game (of v0.8.2).
The issue does not occur in the Unity editor.

### Details
Provide some additional information:

- UltraStar Play version: v0.8.2
- Operating System: Tested on Android and Windows

**Comment by achimmihca** [comment]
> [ERR] Graphics.CopyTexture called with null destination texture

I will look into this.

**Comment by achimmihca** [comment]
The null texture was not the root of the issue.

In general, the shader transition does not work in the built game.
I tested this with a jpg image as transition texture with the same result. It only works in the Unity editor.

@jean-moreno , could you please have a look? Does the scene transition work for you in the built game?
You can fork the branch anst/fixes if you want.

**Comment by achimmihca** [comment]
It's not just the scene transition, the `_UI_SHADOW` does also not work in the built game.
I think Unity uses a different (fallback) shader for some reason in the built game.

**Comment by achimmihca** [comment]
> I think Unity uses a different (fallback) shader for some reason in the built game.

Yes! When setting "Player settings > shader settings > strict shader variant matching", then Unity does not use a fallback shader and instead shows a bunch of errors and a pink error shader.

**Comment by achimmihca** [comment]
Will be fixed with https://github.com/UltraStar-Deluxe/Play/commit/4aac5be7e67077584eaacfa7ff3bd55916366b5a

My workaround: use float variables in the shader instead of preprocessor defines. Works for me.
@jean-moreno feel free to find the actual root of the issue.

**Comment by achimmihca** [comment]
Sadly, the shader still does not seem to work on Android. But there is no error message or error shader when enabling "strict shader variant matching". What a nuisance.

**Comment by jean-moreno** [comment]
I don't have enough time to test, but I think you can replace the `shader_feature_fragment` with `multi_compile_fragment` directives in the shader code.
The former will only include the variants that are used by materials at build time, whether the second will always compile all variants regardless of their usage, so that they can be loaded at runtime in the build.

**Comment by achimmihca** [comment]
> multi_compile_fragment 

This did the trick. Thanks!
But it's still not working on Android.

**Comment by jean-moreno** [comment]
Nothing in the log at all, related to shaders, on Android?
That's weird 🤔

**Comment by achimmihca** [comment]
It now works on Android as well. No idea why 🤣
