### ISSUE TITLE
Cannot play videos on linux

### ISSUE THREAD

**Issue by g3n35i5** [UltraStar-Deluxe/Play#379]
Issue type: Bug report

I've tried multiple formats/codecs (h264/mp4, AV1, webm).

### Actual behaviour
UI note that video cannot be played, debug log states the following:
```log
[ERR] VideoPlayer cannot play url : /mnt/media/karaoke/Ed Sheeran - I See Fire/Ed Sheeran - I See Fire.mp4
```

### Expected behaviour
Video plays.

### Steps to reproduce
- Download and run [latest release for linux](https://github.com/UltraStar-Deluxe/Play/releases/download/v0.8.2/UltraStarPlay-v0.8.2-Linux64.zip)
- Try to open/sing a song

### Details
Provide some additional information:

- UltraStar Play version: v0.8.2
- Operating System + version: ArchLinux (x64, 6.1.1-arch1-1 SMP PREEMPT_DYNAMIC)

**Comment by bohning** [comment]
https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html

**Comment by g3n35i5** [comment]
You're right, this works. Changing from

```
mediainfo Ed\ Sheeran\ -\ I\ See\ Fire.webm
Video
ID                                       : 1
Format                                   : VP9
Codec ID                                 : V_VP9
```

to

```
mediainfo output.webm
Video
ID                                       : 1
Format                                   : VP8
Codec ID                                 : V_VP8
```

with the help of
```
ffmpeg -i Ed\ Sheeran\ -\ I\ See\ Fire.webm -c:v libvpx -crf 30 -b:v 0 -b:a 128k -c:a libopus output.webm
```

helps and plays the video. Bug the documentation states that VP9 is supported on linux, any thoughts on why this doesn't work for me?

**Comment by bohning** [comment]
You mean the documentation of US Play? Or of Unity? I believe, but I am not positive, that VP9 is not (yet) supported on Linux:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1497707/215264915-19228f57-8889-4cf2-9c83-dab2261c3933.png">

**Comment by achimmihca** [comment]
> But the documentation states that VP9 is supported on linux

If you can point me to the documentation, I can fix it. VP9 is not (yet) supported on Linux.

Media file support will be improved with #362

**Comment by g3n35i5** [comment]
You are right, I read the documentation wrong. Thanks for your help!
