### ISSUE TITLE
Assets Folder Structure

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#38]
Issue type: Development discussion

### Problem or question to be solved

The current folder structure is mixing different approaches:
  by scenes
  by asset-type (e.g. material, sounds, scripts... )
  by architecture level (e.g. model, persistence, ui, ...)
  by feature (e.g. microphone recording, showing highscores)
The current structure, is cluttered IMO.

### Suggested solution/

Structure stuff by scenes where possible. I think this naturally connects related assets (e.g. the scene itself, scripts of the scene, prefabs of the scene).

However, this only works for stuff that is related to a single scene. For everything else (e.g. persistence layer, libraries, general graphics for the UI, general sound effects) I would create a "Common" folder, which holds the stuff that is used in more than a single scene.

Of course, special folders (e.g. "Editor") are an exception to the structure.

Furthermore, I suggest to use PascalCase to name folders. This fits with the C# guidelines and other folders inside Unity. Thus, it would be "SongSelection". It would not be "songSelection" or "song-selection" or "Song Selection".

Example of what I have in mind:
```
                            - Assets
				- Editor
				- Common	
					- Persistence
					- Sounds
					- Graphics
						- Icons
					- Recording
						- PitchTracker
						- MidiUtils.cs
                                                - MicrophoneListener.cs
				- Scenes
					- Settings
						- SSettings.unity
						- SSettingsController.cs
					- SongSelection
						- SSongSelection.unity
						- SSongSelectionController.cs
						- SongButton.cs
						- SongButton.prefab
					- SongEditor
						- SSongEditor.unity
                                                - SSongEditorController.cs
                                                - DeleteSelectedNoteButton.cs
                                                - VerySongEditorSpecificIcon.png
```

### Your opinion on the topic

Structuring information in folders is tricky. I am sure there are various threads and opinions.
For an example that discusses folder structure in Unity, look [here](https://forum.unity.com/threads/best-practices-folder-structure.65381/#post-2973760)

**Comment by achimmihca** [comment]
Note that the additional "src" folder is unecessary IMO. This is commonly used in Java projects and others as the root of the logic and asset resources. However, in Unity we already have the "Assets" folder, which does this very job.

**Comment by achimmihca** [comment]
I noticed that the scenes at the moment have a prefix "S" and a suffix "View". This is redundant. Furthermore, for me a scene and view are not the same. A scene is a specific Unity construct. A View is some graphical user interface for a specific task. So I can imagine having different views in the same scene (e.g. navigating through different views of settings could be implemented in a single scene).

Thus, I suggest to only use the "S" prefix.

For the main logic that handles a specific scene, I suggest to use "Controller" as suffix, which has already been done. Then it would be "SSettings.unity" and "SSettingsController.cs".

**Comment by achimmihca** [comment]
Note that the suggested folder structure is grouping different asset-types by function. So there could be scripts, scenes, images, prefabs, etc. in the same folder, if they implement a common idea.

**Comment by basisbit** [comment]
sorry for my late reply once again...

Regarding the folder structure, yes, we absolutely should change it to what would be typical for Unity projects. I only know best practices from java projects and also would not do all the prefixes again nowadays. Changed my job in between, first I learned bad practices, now I am learning good practices 😄 
The S prefix was originally intended to be a marker for "screen" files - and were splitted into the Unity View/Scene and a code class (controller).

**Comment by basisbit** [comment]
I spent some time trying to find best practices for Unity projects but mostly only found outdated stuff. From what I learned, every Unity Scene should have a Controller/Code-file which handles the scene-UI specific code and also handles interaction between the unity-scene-objects and other code classes.

C# naming guidelines should be followed. I absolutely agree to sticking to standards of unity/c# dev environment

**Comment by achimmihca** [comment]
I dont mind the prefixes if they are used to convey information (e.g. I for interface, A for abstract stuff, E for enum, and maybe S for scene).

Anyway, I already used my suggested structure for what I am doing with Ultrastar Play at the moment. It's a starting point, and we can go from there. Anyway, I think its better than the original stuff ;)

**Comment by achimmihca** [comment]
BTW:
I am making some good progress so far with basic features. One can select from a list of songs to play. Playing the music with video synchronized (still a bit laggy), showing notes and lyrics works.

I also managed to integrate some pitch detection (implementation from https://archive.codeplex.com/?p=pitchtracker). However, there is a delay of about 200ms (probably related to Unity API or C# performance). I am unsure if this will be sufficient for practical singing. Anyway, one can get the idea from this and its ok for a prototype.

**Comment by achimmihca** [comment]
I want to clean up and polish the prototype of what I have so far before I will create a pull request here.
It probably will take few weeks more.

**Comment by basisbit** [comment]
ooh, that sounds so amazing! I am so happy there are finally some more people contributing to this game! I'll be infinitely grateful when I don't have to read objective pascal code any more to fix stuff in UltraStar Deluxe 😍

**Comment by basisbit** [comment]
@achimmihca could you please create a pull request containing your changes already? I'd like to continue coding but don't really want to get tons of merge conflicts with all the changed folder structure and so on. You have write-permissions on this repository here, so maybe we can continue work here either on master branch or on a feature branch?
Thanks!

**Comment by achimmihca** [comment]
I opened a PR, but I cannot merge it. You have to review and accept it before.

I also updated the CONTRIBUTION file, to provide a good starting point for the new code.

You have to adjust in Config.xml the <SingDir> tag and the mic of a player profile.
