### ISSUE TITLE
Calculate time in the song (e.g. in seconds) from a given beat and bpm of Ultrastar file

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#39]
Issue type: Development discussion

I try to calculate note positions based on the BPM and beat in the song that is given in Ultrastar files.
My problem is that the values I calculate are not matching the speed when playing the file in USDX.

# Example
I create a simple song file. It has 120 BPM and a single note with a duration of 10 beats:
```
#TITLE:EmptyTitle
#ARTIST:EmptyArtist
#MP3:EmptyArtist - EmptyTitle.mp3
#BPM:120
#GAP:1000
: 0 10 5 bla
- 15
E
```

The note of this file when viewed in Yass (or played in USDX) has a duration of 1.25 seconds.
However, with 120 beats per minute, it holds that
1 beat has a duration of 60 [s] / 120 [b] = 0.5 [s/b],
thus 10 beats have a duration of 5 [s] .
This is obviously different from the 1.25 seconds the note has in Ultrastar.

So, what is happening here? Did I make a mistake or is BPM in Ultrastar not "beats per minute"?

**Comment by basisbit** [comment]
Best practice for BPM values in usdx files is to always use a multiple of the actual song BPM, so that it is between 200 and 400.
`: 0 10 5 bla` means the syllable bla with a pitch of 5 starts at beat 0 of the current sentence and ends at beat 10 of the current sentence.

**Comment by basisbit** [comment]
the mp3 file you are using, is that maybe encoded in variable bitrate?

**Comment by achimmihca** [comment]
The MP3 is irrelevant.

**Comment by basisbit** [comment]
time is relative in usdx and YASS. So, if you use a file with variable bitrate instead of coded bitrate, depending on ffmpeg version used, the pointers->timestamp conversion is off. In USDX, the current playback position of the played audio frame is what tells the code what the "current beat" in game is.

**Comment by basisbit** [comment]
I am just trying to understand why the values are off there, because the way that you calculated should be correct. I quickly checked the relevant code in usdx and yes, your calculation should be correct.

**Comment by achimmihca** [comment]
Found the answer: http://yass-along.com/beats/

**Comment by achimmihca** [comment]
You can think of BPM in Ultrastar files not as "beats per minute" but "bars per minute" in four-four time (Viervierteltakt).
Thus, one has to multiply with 4, to get what is commonly known as "beats per minute".

This fixes the mismatch I had in my calculation: 5 [s] / 4 = 1.25 [s]

**Comment by basisbit** [comment]
lol, never realized that before. Anyways, found that now in the code of USDX: https://github.com/UltraStar-Deluxe/USDX/blob/master/src/base/UFiles.pas#L168

**Comment by achimmihca** [comment]
Yeah, you have to know this to get it right...

Anyway, displying the lyrics is now in sync with the music in my prototype. Last important thing missing now is recording notes. Yay!
