### ISSUE TITLE
The macOS Version v0.9.0 does not include an .app file

### ISSUE THREAD

**Issue by Loewe1000** [UltraStar-Deluxe/Play#390]
Hi, 

I've just downloaded the v0.9.0 of UltraStar-Play for macOS, but if i extract the .zip file,
I just get a "Contents" folder which normally is inside the .app file (as far as I know).

Is there any chance, that packaging the mac .zip for v0.9.0 failed?

**Comment by achimmihca** [comment]
Indeed, looks like the script zipped the app folder itself.
Does it work when you rename the folder (the parent folder, which contains `Contents`) to en with ".app"? Not sure if macOS allows this.

I will upload a fixed version soon.

BTW: I just bought myself a Macbook for development. So hopefully, this will not happen again.

**Comment by Loewe1000** [comment]
Thanks for the quick answer.
I could fix the issue by creating a Folder named "UltraStar Play.app" and copy the "Contents" folder inside.

**Comment by achimmihca** [comment]
I re-uploaded the macOS build
