### ISSUE TITLE
cant use touch on surface

### ISSUE THREAD

**Issue by ownstar23** [UltraStar-Deluxe/Play#396]
When playing on my Surface Go 3 i am not able to use touch to navigate through the game. For example i can not scroll with my fingers through the songs or even click a button.

- UltraStar Play version: 0.9.0
- Windows 11 Home

**Comment by achimmihca** [comment]
Does the keyboard work?

If yes, then navigate to "Settings > Develop" and check whether the option "use custom events for input actions" changes anything.

**Comment by ownstar23** [comment]
Keyboard works but the option "use custom events for input actions" changes nothing. 

I just found out that when im holding a button with a finger and clicking that same button with another finger the game clicks that button. It seems to behave like a left mouse click. But thats very uncomfortable and scrolling is not possible. 

I would expect a normal touch behavior like any other app on my surface, for example spotify, where you simply can scroll and click with one finger.

**Comment by ownstar23** [comment]
closing was a mistake.

**Comment by achimmihca** [comment]
> I would expect a normal touch behavior like any other app on my surface, for example spotify, where you simply can scroll and click with one finger. 

Me too, this is how it should work.
That said, I don't have a Windows touch device to test this.

It may just be some configuration issue with Unity or the Input Actions.

Anyone here has a Windows touch device to debug this?

**Comment by achimmihca** [comment]
Does it work when you connect a regular USB or Bluetooth mouse? @ownstar23

**Comment by ownstar23** [comment]
I just found something interesting: the described behaviour seems only to appear when playing in "FullScreenWindow". In "Windowed" the touch works as expected and i can click and scroll through songs with my finger. 

USB connected mouse works but changes nothing with touch behaviour.

**Comment by ownstar23** [comment]
i investigated the problem a little further: the problem still exists in "windowed" mode, it worked at the beginning because the window was so small that pointing with one finger was recognized as two fingers. When im draging the window to a normal size the false behaviour still exists. 

It has to do with the Input Actions: When i opened the repo in unity, "Press (Multi-Touch)" was selected as "click".
![Press_Multi-touch](https://user-images.githubusercontent.com/125564423/220098857-6eb59930-27e9-457f-8ab5-5715d12a3d3e.png)
I Changed it to "Tap" and Buildt the Project. After this i was able to navigate through a double tap with my finger in the game
![Primary-Touch_Tap](https://user-images.githubusercontent.com/125564423/220098898-52c8be1d-8ffb-4518-a93c-05323581bfcc.png)
As next Step i tried the action "Press (Single-Touch)", but this doesnt work. Now i cant press a button with my fingers.

**Comment by achimmihca** [comment]
Thanks for testing this.
Might be worth to ask about this issue on the [Unity forum](https://forum.unity.com/). Not sure if it is a Unity bug or something we configured the wrong way.

**Comment by ownstar23** [comment]
It seems to be a problem with Unity (current editor version: 2022.2.4f2). I opened the repo with a newer editor version (2023.1.7f1) and built the game. Now the touch is working as expected, i can click and even scroll through the songs. (tested on Lenovo Yoga C940 and Microsoft Surface Go 3)

I guess Melody Mania is also built in editor version 2022.2.4f2, because the touch on my Surface Go 3 is not working. I would suggest to change to unity version 2023.1.7f1, even though i cant say if that has negative effects on other components.

**Comment by achimmihca** [comment]
The beta branch of Melody Mania uses Unity 2022.3.6f1.
Please test whether this fixes the touch issue on Surface devices.
