### ISSUE TITLE
How does USDX calculate the player score?

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#40]
Issue type: Development discussion

### Problem or question to be solved

When the player sings a note at the correct pitch then he gains points.
Question is, how much points does he get for a given song, note in the song and range of the note that was sung correctly?

I noticed that USDX is giving 10000 points when everything is sung correctly. Let this be MAX_SCORE.
How is this amount distributed over the notes? My intuition would be that golden notes bring twice as much points than normal notes and freestyle notes are not contributing to the score.
Is this true?

Then this would be:
MAX_SCORE = normal_note_points + golden_notes_points
MAX_SCORE = (any_note_points * normal_notes_portion) + (2 * any_note_points * golden_notes_portion)
MAX_SCORE = any_note_points * ((normal_notes_portion) + (2 * golden_notes_portion))
any_note_points = MAX_SCORE / ((normal_notes_portion) + (2 * golden_notes_portion))

normal_notes_portion = beats_of_normal_notes / total_beats_of_song
golden_notes_portion = beats_of_golden_notes / total_beats_of_song

Gaining points when singing a portion of a note would thus be:
score_for_this_portion = (beats_of_note_sung_at_correct_pitch / total_beats_of_note) * any_note_points * (isGolden ? 2.0 : 1.0)

# Score labels

Related to this question is the labels that are associated with a certain score.
E.g. score > 9000 is "Ultrastar", score > 8000 is "Superstar" (or similar).
Is there a complete table for this?

**Comment by basisbit** [comment]
Yes, multiplier values are for freestyle notes = 0, normal = 1 and golden notes = 2. Simplified explanation: At the beginning of the song, total sum of the multiplier values for the notes is added up for all notes, then MAX_SCORE/totalNotesPoints=newMultiplier is calculated or similar.
Beware that up to 1000 points of the MAX_SCORE is left over to give extra points for perfectly sung lines. 

The relevant code in USDX is mostly here: see https://github.com/UltraStar-Deluxe/USDX/blob/master/src/screens/controllers/UScreenSingController.pas#L1670

**Comment by basisbit** [comment]
Score labels from USDX see https://github.com/UltraStar-Deluxe/USDX/blob/114ff0c11e8f2c415404e75db213f97a744f487b/src/screens/UScreenScore.pas#L1434

**Comment by basisbit** [comment]
oh, and the "perfect line" score is already given when 95% (or better) of the possible points of that line are achieved

**Comment by achimmihca** [comment]
I implemented this in PlayerScoreController

- max score for a song is 10000 points

- 1000 points of it can be achieved for singing perfect sentences. A perfect sentence gives at least 50 points. Thus, if there are more than 20 sentences, then you do not need to sing all sentences perfectly to get the full perfectSentenceBonus.
- a sentence counts as "perfect" when 95% of its note duration has been sung correctly

- 9000 points can be achieved by singing the notes correctly.
- golden notes give twice as much points as normal note
- points for a note are given linearly for the duration of the note that was sung correctly.
- the selected difficulty defines the rounding distance for singing correctly: easy = 2 midiNotes off still counts as correct, medium = 1 midiNote off still counts as correct, hard = midiNote must be hit perfectly. This is also what USDX is doing.
