### ISSUE TITLE
Strings branch

### ISSUE THREAD

**Issue by BanCrash** [UltraStar-Deluxe/Play#401]
Hi @achimmihca , I understand the reason of having a private repository but what do you think of having a public branch where post from time to time the translatable strings, in order to have them translated for the Steam release? That would allow translators to have the chance of take their time to translate the strings instead of having to translate them in a rush.

Since it won't be an option to compile the project for testing the translations there will be strings that have to be fixed in the future, but that's not a big deal since the fixes can be added in future Steam updates.

**Comment by basisbit** [comment]
Most of the UI and translatable strings are her ein this repository. So, just doing translations for the public stuff should be all that is needed. The other stuff eventually also will be published to here, too.

**Comment by basisbit** [comment]
> Since it won't be an option to compile the project for testing the translations there will be strings that have to be fixed in the future, but that's not a big deal since the fixes can be added in future Steam updates.

Of course you can compile and test this here project, and get like 95% of the UI and features and so on.

**Comment by BanCrash** [comment]
Okay then!

**Comment by achimmihca** [comment]
When the new UI is ready, I will merge the translation properties to the public repo and back, such that the community will be able to contribute translations.

However, the new UI is not ready yet.
