### ISSUE TITLE
Cannot set song path without completely typing it by hand

### ISSUE THREAD

**Issue by a3nima** [UltraStar-Deluxe/Play#402]
Issue type: Bug report

### Actual behaviour
I want to add the existing song folder in the settings menu ("song library"). 
the arrow symbol opens the explorer but does not let me choose the directory.
i cannot copy and paste the directory into the typing field. (not right click, not ctrl+v)
The only way seems to be to type the path by hand.

### Expected behaviour
I should be able to choose the directory with the arrow symbol 
I shold be able to copy and paste into the typing field.

### Steps to reproduce
It s just as it is right now.

### Details
Provide some additional information:

- 0.9.0
- Windows 10 Home latest version
- there wont be a log available I guess

/edit: i see the arrow symbol is to get to the entered directory. but it would be good to have a function+icon to browse there

**Comment by achimmihca** [comment]
Pasting should work (ctrl+v)

Yes, there will be a button to open a folder chooser dialog in the future.
This has already been implemented die the Steam release in the private repo.

**Comment by a3nima** [comment]
thanks for the response! strange thing, somehow copy and paste did not seem to work, but now it does :D
