### ISSUE TITLE
Solo/Band quickplay mode / jukebox mode with spontaneous singing

### ISSUE THREAD

**Issue by franciscopassos** [UltraStar-Deluxe/Play#405]
Issue type: Feature request

This is a feature of Rock Band, where you can set the game to just be playing songs from the entire collection (though it might be restricted to a playlist) without note guidance, and where at any point if someone wants to play an instrument / sing, they can come in into the middle of the song, note guidance comes in and they can start playing / singing.

I think this was a phenomenal way to have background music in a party, and there can be moments where people are actively singing / playing, others where the music is just playing, and people can simply react to a cool song when they hear it and go sing.

**Comment by basisbit** [comment]
This sounds like an extension of the Jukebox mode which the old UltraStar Deluxe also has. Being able to just quickly grab a microphone and see the graded lines would probably also be fun.

Not sure if the note pitch lines should be hidden, unless the game detects a player (and then auto-hide again if there was no pitch input detected for some time), by listening for noise above the specified threshold.

Should this be pure single-player, or automatically have the same amount of players as there are microphones (currently soundcards) configured and detected?

**Comment by franciscopassos** [comment]
Agreed, this sounds like an extension of the Jukebox mode.

Single or multiplayer would be awesome. Your idea for automatic detection is really solid and it reduces the friction of joining or leaving a song.

Support for any of the configured microphones/player number would rock.

All of these aspects are optional and can be worked on incrementally.

**Comment by achimmihca** [comment]
What happens if the user decided to leave the mode by singing?
Does the next song start automatically (i.e. continue jukebox mode) or the singing results (i.e. return to normal game)?

I think such a mode could be added implicitly:

- start into "jukebox mode with spontaneous singing" when no player input is received for some time (e.g. 30 seconds) although there are notes to sing.
    - When the mode starts then the UI is hidden.
        - Maybe one should show some small icon or label to educate the player "Entered jukebox mode. Start singing to exit."
        - Maybe one could show an additional "start next song" button" to skip the current song without leaving the mode.
    - When the mode has started and the song ended without any scored points then the next song is selected randomly and starts automatically.
    - When the mode is left by singing into a mic, then the UI shows up again and the game continues normally with singing results (no more auto start of next song).

**Advantages**
This implicit mode has the advantage that no additional UI or configuration is needed. It could be implemented rather easily.
The players and mic configuration is the same as usual.

**Disadvantages**
This implicit mode does not include a dynamic addition / removal or players and their mics. I am unsure how this should be achieved anyway.
Is dynamic additional / removal of players relevant? One could just start the game with one or two generic player names and then let go.

What do you think? Would this implicit mode work for you?

**Comment by franciscopassos** [comment]
Hello, thank you for your reply and suggestions.

Implicit triggering the UI sounds like a great idea, and a lot of your suggestions sound spot on. Implicitly exiting the mode would not fit the purpose (meaning it would detract from the experience originally in Rock Band). I'll elaborate a bit below.

First the suggestions that really fit the feature request:

* The UI showing no notes, only the label (e.g. Party mode, sing to see the notes)
* The notes appearing and the scoring starting when someone sings into the mic
* Having a next song button (basically like a playlist, perhaps with a shuffle option that is togglable)
* Starting with 1-2 generic player names is entirely fine for this mode. Blue player, red player, something like that. People in a party will switch places at the mic anyway, so the name is not important.

Some context from Rock Band:

Adding/removing players was always easy, because the instruments had buttons and touching one of them popped up a menu that allowed joining the song with that instrument or removing that instrument. When joining, a generic player with no name and no profile would be used. For the mic, the user needed to use the remote, to access the same overlay.

With that in mind, here are some additional things to perhaps consider:

* Moving the mouse / pressing enter might make overlay options appear, like "exit party/jukebox mode", "start singing", or "add/remove player" (that last one is advanced and might not be needed considering the default wiring and the automation deciding when to show/hide the UI).
* Leaving "party/jukebox mode" is never implicit. Once in that mode, you stay in it until you explicitly select the option to leave it. That means that when a song ends, the next one gets started automatically, regardless of whether any singing took place or any other implicit signals.
* No singing results are displayed in "Party/Jukebox mode". The idea of this mode is to run on the background at parties, and the music keeps running. People can join and depart freely. Imagine having a chat with friends, then a song comes up and someone says "sorry I need to sing this one", goes, sings it, comes back and keeps chatting. If people want to change the mode to something more serious, they can. Until they do, the music (the party) goes on.
* Notes/UI could disappear (revert to just visible jukebox) when
  *  No notes were sung in a song that just ended (implicit)
  * After a sufficiently long period with no notes being sung (also implicit, but it is unclear how long that should be, there are songs with long instrumentals)
  * A user selects "remove player(s)" from the overlay menu

**Comment by achimmihca** [comment]
Thanks for the clarification.
In this case, I would not suggest to do anything implicit. It should be an extra game mode.

Maybe it could be implemented as one of the game modifiers. Maybe it could even be implemented in a user provided script that is loaded at runtime (a user defined game mode).

**Comment by franciscopassos** [comment]
This is excellent, thank you for building this! Where do I find this option in Melody Mania?
