### ISSUE TITLE
Replace Y-Button on controler with "select random song" instead of "open song editor"

### ISSUE THREAD

**Issue by m4akus** [UltraStar-Deluxe/Play#409]
Issue type: Feature request

### Actual behaviour
Currently the Y-Button on a XBOX-Style controller under windows opens the song-editor

### Expected behaviour
I think it would be more useful to have the Y-Button select a random song instead, because when using the controller i suspect the users are currently playing and not working on new songs

BTW: the docs currently don't mention CTRL+R (i found that it selects a random song), would i be possible to expand the docs?

**Comment by achimmihca** [comment]
You should be able to edit the docs when you have a GitHub user.
It's a wiki after all.
