### ISSUE TITLE
Monospace font instead of proportional font for song timeline

### ISSUE THREAD

**Issue by m4akus** [UltraStar-Deluxe/Play#411]
Issue type: Feature request
### Actual behaviour

Currently the timer on the bottom right in the singing-scene uses a proportional font. This leads to permanently changing scale or distances on the text-timeline

![image](https://user-images.githubusercontent.com/82236082/223806403-7f0330ff-5f2e-40d6-98df-0a84f2247a79.png)

### Expected behaviour

The use a monospace font for the countdown would mitigate the change of scaleing for the timeline

**Comment by achimmihca** [comment]
A fixed width would for the label would also solve this issue.

Anyway, a new design is currently under development, which handles the timeline differently, namely in an overlay so you do not see it all the time (more like YouTube basically).

**Comment by m4akus** [comment]
Ah nice, looking forward to the Steam-Release. Will there be a Option to have it enabled all the time, because i actually really like the overview it gives when it comes to pauses like solos etc.

**Comment by achimmihca** [comment]
No such option is planned at the moment.
Maybe in a future release
