### ISSUE TITLE
Loop short videos

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#416]
### Actual behaviour

The video stops at the last frame when it reaches the end, even if the audio continues.

### Expected behaviour

It would be nice to have a looping function for short videos.
This would allow to use [VJ loops](https://www.beeple-crap.com/vjloops) and other [short videos](https://pixabay.com/de/videos/mann-wolken-spiegel-see-himmel-64729/) for songs of any length without manual adjustments.

As a rule of thumb: if the video length is less than half of the audio length then the video should be played in a loop.

**Comment by achimmihca** [comment]
This has been implemented for the Steam release

**Comment by basisbit** [comment]
Can this be disabled somehow? It is a rather often occurence that videos are just a few seconds shorter than the TXT file or the audio file. As far as I remember, USDX so far then showed the last frame, which worked well (or does it fall back to the background image of the song maybe?). This could probably be a custom tag in the headers of the txt file

**Comment by basisbit** [comment]
> As a rule of thumb: if the video length is less than half of the audio length then the video should be played in a loop.

Oh, never mind. That should work well.
