### ISSUE TITLE
Party Mode with Items "Lyric Looting"

### ISSUE THREAD

**Issue by DerDorius** [UltraStar-Deluxe/Play#419]
Issue type: Feature request

## Description
Add a new game mode to MelodyMania called somthing like "Lyric Looting". In this mode, items will appear on certain notes in a song, which can be collected by hitting the correct pitch on that note perfectly.
![image](https://github.com/UltraStar-Deluxe/Play/assets/77979816/44a728e6-091a-420e-894d-9db4482dfeca)

The items could be similar to those in the popular game Mario Kart:

- Rocket (Bullet Bill): Automatically hits all notes for a short period of time.
- Mushroom: Grants an instant 300 point bonus.
- Red Shell: Deducts 100 points from the player with the highest score.
- Green Shell: Deducts 50 points from a random player.
- Blue Shell: Deducts 300 points from the player in first place.
- Banana: Deducts 40 points from the player who collected the item.
- Star: Plays the song at 1.3x speed for a short period of time.
- Golden Mushroom: Grants a points multiplier for a short period of time.
- Blooper: Covers the screen with ink, making it difficult to see the lyrics and notes. This benefits players who know the song by heart.
- Lightning: Mutes the music for a short period of time.
- This mode will add a fun and competitive element to MelodyMania, making it more enjoyable for players who want a more dynamic experience.

It's also worth noting that some items can have negative effects on the player who collects them. For example, the banana item deducts points. However, this adds an extra layer of strategy to the game. Skilled players who know the song by heart might choose to collect items that negatively impact their opponents, such as the lightning item that mutes the music for a short period of time. This element of risk and reward can make the gameplay more exciting and strategic, as players must decide whether to collect items based on their current position in the game and their familiarity with the song being played.

## Implementation
The items can be implemented as small icons that appear on certain notes in a song. When a player hits the correct pitch on that note perfectly, the item will be collected and the associated effect will be triggered.

The effects of the items can be balanced and adjusted based on feedback from players, and different songs can have different item placements to keep the game fresh and exciting.

## Conclusion
By adding a "Party Mode with Items" to Ultrastar Deluxe, the game can become even more entertaining and engaging for players. This feature can add a unique twist to the traditional karaoke experience, making it more enjoyable for players of all skill levels.

**Comment by achimmihca** [comment]
Thanks for the suggestion! I think this is a neat idea.
I think such a game mode could be implemented as user defined, runtime loaded script #394

**Comment by achimmihca** [comment]
There was a suggestion in #243 for a game mode called "last one standing":
- After a certain percentage of the song, the player with lowest points is out.
    - This is a common game mode for racing games.

The opposite would also be possible:
- After a certain percentage of the song, the player with highest points claims the current best place while the others continue to sing for the remaining places.
    - This might be more pleasant from a psychological point of view.

Runtime loaded scripts should enable to add such game modes.

**Comment by DerDorius** [comment]
Started Open Source Development here:

https://github.com/DerDorius/ItemRumbleMelodyManiaMod

**Comment by basisbit** [comment]
That sounds very promising! Let me know if you want a separate repository for collecting such mods/addons here in the organisation.
