### ISSUE TITLE
Desync of Song Playback and Midi/Lyrics in Editor when using variable bit rate (VBR)

### ISSUE THREAD

**Issue by Shildifreak** [UltraStar-Deluxe/Play#427]
Issue type: Bug report

### Actual behaviour
I tried hours to position the notes in a song correctly, messing with BPM etc., but they were always slightly out of sync.
I noticed that the desync was sometimes early and other times late even if I did not change anything with the notes: just playing the part I was working on vs playing the whole song.
Eventually I found a forum post mentioning checking Karaoke Songs for variable bit rate (VBR) and converting them to constant bit rate (CBR).
After using ffmpeg to do just that the problem was immediately gone.

### Expected behaviour
Ideally the synchronisation should just work.
Alternatively there should be some indication/warning message that VBR vs CBR is a thing and songs should use CBR encoding.
If I understand correctly, this is only a problem in the editor, not in normal gameplay because there the songs are always played from the beginning.

### Steps to reproduce
1. Open the StandaloneLinux64
2. Create new Song, insert mp3 with variable bit rate, place some notes
3. play the song starting at different timestamps
4. notice how the notes are sometimes early and other times late

### Details
- UltraStar Play version: 0.9.0 (also 0.7.0, but I updated to see if maybe it was already fixed and some other bugs are :) but this it isn't)
- Operating System: Ubuntu 22.04.3 LTS

This may be related to the Unity bug mentioned in issue #362

**Comment by achimmihca** [comment]
> This may be related to the Unity bug mentioned in issue https://github.com/UltraStar-Deluxe/Play/issues/362

Indeed, this is probably the same issue as in #323 

It should be fixed in Unity 2023.2, which should be released early in 2024

![Chart for 23 3 Blog](https://github.com/UltraStar-Deluxe/Play/assets/14967033/d4ffeada-68d7-4892-b201-e9bf5be77f0a)

**Comment by achimmihca** [comment]
> It should be fixed in Unity 2023.2, which should be released early in 2024

Unity 2023.2 has been released.
It seems to have fixed the issue, at least for https://github.com/UltraStar-Deluxe/Play/issues/323
