### ISSUE TITLE
How to get the pitch detection ?

### ISSUE THREAD

**Issue by happyriri** [UltraStar-Deluxe/Play#431]
Hi,

Just for my information I want to know how Ultrastar Play know the pitch detection ?

I don't find it on the repository.

Thanks !

**Comment by basisbit** [comment]
The audio recording code is in https://github.com/UltraStar-Deluxe/Play/tree/master/UltraStar%20Play/Packages/playshared/Runtime/Audio/Recording

Camdiff was the initial one, and Dywa is the wavelet math based current one:
https://github.com/UltraStar-Deluxe/Play/blob/master/UltraStar%20Play/Packages/playshared/Runtime/Audio/Recording/DywaAudioSamplesAnalyzer.cs

**Comment by happyriri** [comment]
Thanks !
And do you use MIcrophone of Unity or you use a custom Microphone ?

Thanks in advance !!
