### ISSUE TITLE
new libs: dependency injection (Zenject, UniInject, ...)

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#44]
I want to make use of some libs for the UltraStar Play (let's call it USDP ;) ) codebase.
This is a request for comments. Anyone agrees / disagrees?

**Zenject**
For dependency injection (aka Inversion of Control)
Asset store: https://assetstore.unity.com/packages/tools/integration/zenject-dependency-injection-ioc-17758
Tutorial on GitHub: https://github.com/modesttree/Zenject

This could make wiring up objects more easy. It could also be used to register the manager instances in a central way and inject them where needed.
I want to try it and see if my expectations are met.

**Comment by basisbit** [comment]
Being a Java developer who uses Spring Boot at work, I love Dependency Injection. Sadly, I don't have any experience with dependency injection in the C# world. With such a project as UltraStar Play (USPlay / USP/?USDP?) we should try to find solutions that will work for a very long time, thus keep amount of dependencies low and only use already established ones which have a large userbase and thus will probably continue to be supported for a long time.

Could you comment this regarding Zenject and UniRx?

**Comment by achimmihca** [comment]
Regarding dependency injection I took a look at Zenject, [adic](https://github.com/intentor/adic/), [RapidIoC](https://github.com/cpgames/RapidIoC).

Zenject is by far the biggest and most used DI lib of these. It can do everything that I wanted. It also checks the validity of the injection, i.e., that nothing is missing.
However, this is pretty heavy-weight lib and I think 90% of it will be unused for USDP. The project seems to have lost the focus on DI.

RapidIoC requires the implementation of an interface IView, which I consider unlucky naming. For me, a view is something in the UI or a specific view on data.
This project does not seem to have any [community](https://www.chillpillgames.com/community.html?p=%2F%3Fembedded%3D1%26embedCookiesBlocked%3D1) behind it.
From the examples that I saw, injection is only done in children GameObject. Thus, this lib dictates the object hierarchy, which I consider a no go.

Adic is a lightweight lib. However, it seems unmaintained and I already had an [issue](https://github.com/intentor/adic/issues/99) with it. Also, the doc says that objects are safe to use (i.e. injection has been done) after the Start method. I consider this too late because it leaves no usable startup method. In contrast, Zenject has objects completely injected after Awake.

---
Anyway, after using Zenject for our code base, I am not convinced that it will be of great help.
I did got rid of references to static instances, e.g. I18NManager.Instance, because these managers can easily be bound and injected.
But it also adds complexity and indirection to the project. For example a context in every scene that must be configured.

I am unsure how to apply DI in a meaningful way in Unity, because in Unity you wire up your object's dependencies in the Editor (e.g. prefabs). Furthermore, there are GetComponent or GetComponentInChildren.
A proper DI solution should handle these cases as well, such that there is a single concept how to bind, find and wire up objects. I don't think Zenject does this for us.

So conclusion: If we do choose an existing DI lib for Unity, then I would go with Zenject.
But I would not do this before we have a guideline and concept for using DI at all.
Maybe a custom solution that is more focused on our problem would be more beneficial.

**Comment by achimmihca** [comment]
I moved UniRx to a dedicated issue

**Comment by achimmihca** [comment]
With some weeks of work I created the dependency injection tool that I was looking for. It's called UniInject.

> in Unity you wire up your object's dependencies in the Editor (e.g. prefabs). Furthermore, there are GetComponent or GetComponentInChildren.

Therefore, the features that I was looking for were

- field, property, method and constructor injection
- cyclic dependencies should be handled, except for constructor injection
- injection should be finished after the Awake() method, such that the injected values can be used in the Start() and OnEnable() methods for setup logic
- no additional interfaces should be required
- no special scene hierarchy should be required
- optional injection
- custom key for injection (but the default is the type of the field that should be injected)
- using GetComponent, GetComponentInChildren, etc. should be done with the same approach as injection of custom bindings
- to facilitate testing, the values of GetComponent, GetComponentInChildren, etc. should be mockable. So in tests the scene hierarchy can be simulated.
- manual injection of fields using the inspector should also be checked when using an annotation

Here is an example:
```
public class ScriptThatNeedsInjection : MonoBehaviour
{
    // Inject property
    // This is optional, which means if no binding is found then it is ignored.
    [Inject, optional = true]
    private SettingsManager SettingsManager { get; set; }

    // Inject field using a specific key instead of the type.
    [Inject(key = "author")]
    private string nameOfAuthor { get; set; }

    // Inject field via Unity's GetComponentInChildren
    [Inject(searchMethod = SearchMethods.GetComponentInChildren)]
    private ChildOfScriptThatNeedsInjection child;

    // This is only a marker attribute. A static check in the editor can verify that the value has been set.
    [InjectedInInspector]
    public Transform referencedTransform;
}
```

Binding values can be done using normal MonoBehaviours that implement the IBinder interface, for example

```
public class DependencyInjectionDemoBinder : MonoBehaviour, IBinder
{
    public List<IBinding> GetBindings()
    {
        BindingBuilder bb = new BindingBuilder();
        bb.Bind("author").ToExistingInstance("Tolkien");
        // The following is equivalent to bb.Bind(typeof(SettingsManager)).ToExistingInstance(SettingsManager.Instance);
        bb.BindExistingInstance(SettingsManager.Instance);
        return bb.GetBindings();
    }
}
```

Using the Inject annotation also enables to check that the values to be injected actually exist.
For instance, if the instance of ScriptThatNeedsInjection does not have an instance of ChildOfScriptThatNeedsInjection below its scene hierarchy, then this can be detected before starting the play mode.
Similarly, a check can be done to verify that the values to be injected are actually bound. In the above example some instance of IBinder in must return a binding for the key "author" or the check will fail.

For tests, the Unity search methods can be mocked. This makes writing tests easier because one does not need to simulate the real scene hierarchy anymore. Example (in a test method): 
`GlobalInjector.MockUnitySearchMethod(scriptInstance, SearchMethods.GetComponentInChildren, new ImplMock());`

A SceneInjectionManager is taking care of finding the bindings and injecting them in the current scene. As I said, this is done in Awake, such that injection is finished when entering the Start method. Such a SceneInjectionManager can be added to the CommonSceneObjects to have injection working in all our scenes.

Using reflection is relatively costly so the first time a scene is analyzed can take some time (around 100ms for a simple scene at the moment). The subsequent times the same scene is opened will be much faster.
There are several possiblities to improve performance:

- use a marker interface and only analyze and inject the scripts with that interface
  (e.g. in the above example ScriptThatNeedsInjection could implement an interface INeedInjection). I consider this the way to go because it is simple and works well. Of course, it has no benefit if every class in the scene needs injection.
- analyze all types of the assembly in the initial loading scene (this takes around 1.5 seconds at the moment). Analyzing all other scenes will be much faster afterwards.

---
Conclusion
Using UniInject gives us the following benefits: less boilerplate code to get instances, better testability,  and static checking of the scene. The same approach (the Inject annotation) can be used to get an instance via Unity search methods (e.g. GetComponentInChildren) or from custom bindings.
There are some performance impacts, but I think these are acceptable for the benefits that we get when using UniInject.

**Comment by achimmihca** [comment]
I am actively using UniInject now and it is a great help.
I will close this issue now.
