### ISSUE TITLE
Backgroud Video Pixel

### ISSUE THREAD

**Issue by Banhammer1919** [UltraStar-Deluxe/Play#46]
Hello, I have a problem with the display of background videos. I have gray pixel errors / overlays. That happens with mp4 / mpg videos. Not at avi videos. I already have all codecs installed. what can this bug be?

Here is a video about the bug:
[Youtube](https://youtu.be/9LtSKRYZCXY)

**Comment by basisbit** [comment]
@Banhammer1919 Thank you for deliberately ignoring the issue creation templates, so now we have to ask you for all the details again. Are you actually using UltraStar Play? That looks more like UltraStar World Party or UltraStar Deluxe. I do not know that theme. Provide some additional information like UltraStar Play version, Operating System + version, ...
