### ISSUE TITLE
Jukebox & Sing Randomization Issue

### ISSUE THREAD

**Issue by sam394** [UltraStar-Deluxe/Play#465]
Issue type: Bug report

### Actual behaviour
In the Jukebox & Sing mod there is a randomization issue when a song finishes playing, the app flashes a bunch of 1 to 2 second clips of songs before landing on the next song.

### Expected behaviour
What is expected in the Jukebox & Sing mod is when a song finishes playing, the app plays the random next song.

### Steps to reproduce

1. Open the melodymania.exe
2. Go to options in the bottom right 
3. Go to Mods menu on the left
4. enable jukebox and sing mod
5. exit the options menu
6. select a song and let it play and finish
7. the mod flashes a bunch of 1 to 2 second clips of songs before landing on the next song.

### Details
End users should not see what songs the system is thinking about playing.(Flashing of 1 to 2 sec clips)
It should just play the next random song.

- Melody Mania version: 1.4.1-beta6
- Windows 11 Home version: 23H2
- if applicable, add a log file

**Comment by marwin89** [comment]
Thanks for the good bug report :) however we don't do support for modifications in general here. Please report this issue to the developer of the Jukebox & Sing Mod.

**Comment by achimmihca** [comment]
@marwin5189, in this particular case, the mod is from me and I asked them to provide some details here on GitHub.

Will take a loom soon.

Sorry for the confusion

**Comment by achimmihca** [comment]
fixed in Melody Mania v1.4.1-beta8
