### ISSUE TITLE
Songs are not accessible when fetched from a NAS

### ISSUE THREAD

**Issue by LoicBrassart** [UltraStar-Deluxe/Play#467]
Issue type: Bug report

### Actual behaviour
Use case: I want to use my home PC to play MelodyMania and fetch songs from a domestic NAS. 
Though my songs are recognized by MMania in the songs list, actual files seem to be unreachable. Thumbnails are replaced by the MMania logo, and running the song gets me a toast error about missing files (Exact message incoming as soon as I get back home) 

### Expected behaviour
I expect NAS-attached songs to be undiscernable from local ones:
- valid thumbnails
- possibility to play it

### Steps to reproduce
Reproducible: [x] always, [ ] sometimes
1. Set up songs on a NAS
2. Connect the NAS to your gaming machine
3. Launch the game
4. List the network folder in the Songs folder list (Settings>Songs)
5. Go to the songs list to play the game
6. Observe that songs from the NAS behave as exposed above

### Details
- Game version: 
- Operating System and version: Windows10 & Synology DS923+ NAS
- Song details, if applicable: Every format I tried
- Attach a log file. To find the log file, see https://melodymania.org/how-to-report-issues

### Implementation hints
None, I'm sorry to say 🤷

**Comment by achimmihca** [comment]
Confirmed, I can reproduce the issue.

Workaround: map the network drive to a local drive
- See [Microsoft website](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d)
- This way, the OS will handle the network file system related details for the game

Anyway, I think this was working out of the box in the past. I will take a look.

**Comment by LoicBrassart** [comment]
Thanks for the workaround.
I think the bug would be better fixed, but at least for now it's playable !

Thanks again, keep up te good work! 💪

**Comment by LoicBrassart** [comment]
Finally got around to test your fix, everything's fine ! 👌 
Thank you again! ;-)
