### ISSUE TITLE
Can't find UltraStar Play.exe for Windows

### ISSUE THREAD

**Issue by rootvasilij** [UltraStar-Deluxe/Play#508]
Issue type: Development discussion

### Problem or question to be solved
Describe the issue to be discussed.

### Suggested solution/s
Suggest some solutions or answers.

### Your opinion on the topic
What is your personal opinion?

**Comment by rootvasilij** [comment]
I can't find UltraStar Play.exe for Windows.

**Comment by achimmihca** [comment]
It is available on the release page. Expand `Assets` section if not done yet.

Note that v0.9.0 is heavily outdated. You are more likely to have a satisfying game experience when using [Melody Mania](https://store.steampowered.com/app/2394070/Melody_Mania/), which is more up to date and has additional goodies for the game.

![how-to-find-exe](https://github.com/user-attachments/assets/01ad1612-65cb-4ea5-a85a-8587f451b6be)
