### ISSUE TITLE
When Sorting with folders, allow image replacement rather than a folder icon.

### ISSUE THREAD

**Issue by ProsciaN** [UltraStar-Deluxe/Play#511]
Issue type: Feature request

### Actual behaviour

When sorting with folders, the images of the folders is just a folder.

### Expected behaviour

Allow the image to be changed, or grab an existing image from the folder.

### Implementation hints

My suggestion would be:
If an image exists in the root of the selected folder, use that image as the folder image
else if there exists subfolders, use the first image found in a subfolder, alphabetically.
else use the generic folder icon used now.

Ex:
Path is ./All_Songs/Artist_Folders/Song_Folders
Enter the All_Songs directory to show a list of Artist_Folders.
If there is an image in Artist_Folder, use that image as the icon for the Artist_Folder
else if there is no image in the Artist folder, check the Song_Folder in Artist_Folder for an image and use that as the image for Artist_Folder.
else use the default folder icon.

**Comment by achimmihca** [comment]
Duplicates #453

The idea came up before but how exactly this should be have has not yet been specified.
Consider to add your suggestion on the original issue

**Comment by achimmihca** [comment]
closed as duplicate
