### ISSUE TITLE
Feature request: Pitch indicator and scrolling notes/lyrics

### ISSUE THREAD

**Issue by TulipKitten** [UltraStar-Deluxe/Play#56]
![file_33655_karaoke_revolution_002](https://user-images.githubusercontent.com/43901982/68336638-cfdd8e80-00ac-11ea-8a0c-46e542e7a073.jpg)

Could this kind of thing be possible to implement? I know a lot of mainstream singing games that have this feature. I'd be more than happy to work on the graphical aspect (I'm fairly competent in both raster and vector programs) if someone wants to work on the coding aspect of this.

**Comment by achimmihca** [comment]
Yes, this is possible to implement.
What exactly do you mean with pitch indicator? At the moment, you have an indication of the pitch by the note that is displayed for it.

**Comment by achimmihca** [comment]
For the song editor, I created a generic viewport for notes that defines where notes are drawn.
After a bit of refactoring, this viewport could be re-used for the sing scene to implement this feature.
Drawing grid lines of the viewport could also be re-used.
