### ISSUE TITLE
new lib: FullSerializer (json (de)serialization for persistence)

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#57]
# Persist game settings
I thought about how to persist game settings.
I argue that we do not need a database because we don't have multiple users that concurrently access and modify the same data. So there is no need for transactions.
Further, the amount of data will be rather small. All of it can easily be loaded in few classes into the RAM at program startup. So there is no need for lazy loading via Proxy or anything like that.
If needed, queries can be written in C# using LINQ.

Thus, my approach for persisting game settings (maybe also player scores, etc.) would be to keep it simple and just serialize an object that holds all the data to a file. At program start, the file can be loaded from file via a SettingsManager.

I find the current implementation for settings in the master using a dictionary and enums a bit weird. Why not skip the enums and the dictionary and put the values to be stored directly in some classes?

Example:

```
public class Settings
{
    public GameSettings GameSettings { get; set; } = new GameSettings();
    public GraphicSettings GraphicSettings { get; set; } = new GraphicSettings();
    public List<PlayerProfile> PlayerProfiles { get; set; } = new List<PlayerProfile>();
}

public class GameSettings
{
    public SystemLanguage language = SystemLanguage.English;
    public List<string> songDirs = new List<string>() { "./Songs" };
}

public class GraphicSettings
{
    public Resolution resolution = GetResolution();
    public FullScreenMode fullScreenMode = FullScreenMode.Windowed;
}

[Serializable]
public class PlayerProfile
{
    public string Name { get; set; } = "New Player";
    public Difficulty Difficulty { get; private set; } = Difficulty.Easy;
    public Color Color { get; set; } = new Color(0, 0.8f, 0, 1);
}
```

As you see, Settings is the root of the settings hierarchy with more specialized classes that hold various fields.
A SettingsManager can load the Settings when they are needed. They can be saved at scene change or OnDisable() or something like that.

---
# Serialize objects to (human readable) strings
I took a look at different ways to serialize such a Settings class and save it to a file.
The requirements:

- serialize basic types including int, string, float, double
- escape strings if needed (e.g. backslashes in paths)
- serialize List and Dictionary
- serialize nested objects (deep serialization)

## System.Xml.Serialization
In C# there is System.Xml.Serialization.
This xml Serialization does not [serialize Dictionaries](https://stackoverflow.com/questions/2911514/why-doesnt-xmlserializer-support-dictionary). Also, you need to annotate some fields (e.g. for nested object serialization).

Although something like [SharpSerializer](http://www.sharpserializer.com/en/download/index.html) might work for us, I would rather focus on JSON for now because XML is more verbose and JSON should be perfectly fine for serializing the Settings.

[Here](https://jacksondunstan.com/articles/3584) and [here ](https://jacksondunstan.com/articles/3303) is a comparison of some JSON serializers for C#.

## Unity's JsonUtility
Unity comes with JsonUtility, which can serialize objects to JSON.
Unity's JsonUtility does not serialize Dictionaries and does not [serialized nested objects](https://answers.unity.com/questions/1322769/parsing-nested-arrays-with-jsonutility.html).

## LitJson
LitJson is a fast and pretty simple lib for Json serialization.
Sadly, LitJson does not support [serialization of floats](https://github.com/LitJSON/litjson/issues/105). Thus, serialization of Vector3, Color and everything else that uses floats does not work either.
It should be relatively simple to implement this missing feature in LitJson.

## Json.Net
Json.Net has [issues with Unity](https://github.com/JamesNK/Newtonsoft.Json/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++unity).
It appears to me as a relatively complex lib (compared with LitJson for instance). So I don't think we want to invest into this.

## FullSerializer
[FullSerializer ](https://github.com/jacobdufault/fullserializer) meets all requirements and was specifically written to work with Unity.
In the [performance comparison](https://jacksondunstan.com/articles/3714), FullSerializer was the slowest. However, I argue that the performace is still sufficient for us. In the test it took 800 milliseconds for 10000 iterations, so a hand full of iterations should finish in few milliseconds.

FullSerializer does not come with a pretty print mode. However, this can be worked around with some lines from [StackOverflow](https://stackoverflow.com/questions/4580397/json-formatter-in-c).

FullSerializer is MIT license.

---
# Conclusion
I don't see the need for a database.
Instead, I suggest a simple POCO structure for the game settings (maybe also for player scores etc.).
And I would persist this POCO structure as a JSON string using FullSerializer.

**Comment by basisbit** [comment]
sounds good so far. Eventually, we still want to find some solution to store player highscores for songs, average scores, something to store debug logs and so on. Logging could be done to file. Highscores could be simplified to only little local storage, and instead integrate it with some online highscore system. Anyways, highscore storage is not really that important yet :D

**Comment by basisbit** [comment]
also, I agree that JSON format would probably be easiest and it is rather easily readable & writeable even for a human.
I am wondering what there would be to store in these settings files, where the Unity JsonUtility is not enough. Should be rather easy to write a few lines of code that also persist dictionaries using a transfer-list and then the usual Unity JsonUtility.

**Comment by achimmihca** [comment]
When I tried the Unity JsonUtility, it did not serialize inner objects. So when serializing Settings, its inner GameSettings and GraphicsSettings were not serialized.
At the moment, I don't have a dictionary in the settings. But it might be possible in the future. Also, JSON basically is a syntax for nested key-value pairs, which is why I think storing a Dictionary should be supported by a JSON serializer.

Of course, one could extend and work with the JsonUtility or some other lib.
However, I was looking for a solution that "just works" and FullSerializer does this so far.

**Comment by basisbit** [comment]
ok, then FullSerializer it is :)

**Comment by Chase22** [comment]
On the topic of settings ( relating to #6 ) do we need a separate libary for storing game settings?
As far as i see PlayerPrefs does that for us using the unity system

**Comment by achimmihca** [comment]
Of course it would work, but it is pretty low level. PlayerPrefs is storing primitives (float, string, int) with a key. This is basically the special case of serializing a Dictionary called "PlayerPrefs".
Using this, you have to implement serialization and deserialization of this Dictionary into your model objects yourself.
In contrast, using a serialization lib this is all done for you.

Think about what needs to be changed to add a new field to the Settings.
With FullSerializer, you just add the new field in the Settings class and you are done -- even if it is a compound object, e.g. Color, Vector3, a List of something, PlayerStatistics or other nested settings.
In contrast, using PlayerPrefs, you have to define a key for the new property, and create custom logic to load and store it. If it is a compound object with multiple fields (maybe even nested, because a PlayerProfile could contain a MicrophoneProfile for example), then you have to write all of this (de)serialization logic as well.

I want to use libraries to be to save myself hours of development time and for better maintainability of future additions that may come.

---
If all the settings are stored in a map, which has been done in #6 then in reality they are unstructured. This results in a not-so-great API to use them. Furthermore, storing non-primitives (such as PlayerProfiles and Lists) is still not handled and requires custom serialization logic.

From the other ticket:

> having a setting for Language literally means creating an enum class for the possible values (duh) and a class to actually use that as a setting

This is a second class that handles serialization. Not needed with my suggested appraoch.

> In terms of upgradability, for more complex things (like per-microphone settings): not sure on that, though worst-case you just create a bunch of really tiny settings that take into account some microphone-specific prefix, that way your deserializers will not break when adding new settings for them.

As I said, storing non-primitive collections is not handled automatically by this approach.

> Obviously I went a different route, but my route might not be the best

I agree. I think using a proper serialization lib is the better approach.

**Comment by Chase22** [comment]
Point taken. I just wanted to bring it up, to avoid implementing something that is already given to us by unity. Maybe going completly to custom serialization is a good route. Just keeping in mind that we then have to the saving and loading of those settings manually. (or at least call the libary at the right times to do it for us)

**Comment by achimmihca** [comment]
FullSerializer is used in the master now and working like a charm so far.
