### ISSUE TITLE
create prefabs for singing screen

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/Play#8]
required [prefabs](https://docs.unity3d.com/Manual/Prefabs.html) are
- [ ] empty note piece
- [ ] hit note piece
- [ ] golden note piece
- [ ] 7 spaced horizontal note lines (background for the notes)
- [ ] box that contains the name and/or avatar of the current player
- [ ] maybe a panel or border for each "voice"/player to support multiplayer on one screen?

**Comment by achimmihca** [comment]
Is it correct that we can use the images of USDX?

**Comment by basisbit** [comment]
That depends. For lots of artwork, yes, because either I may legally relicense them however I want (either I am creator of some of them or the art is public domain licensed or the creators are my friends). In general, yes, we should check all the graphics which are already part of the UltraStar Play project, document the licenses and so on.
I will be in vacation next week and besides traveling through UK, will have a bunch of hours planned to spend on this project.

**Comment by achimmihca** [comment]
I implemented the basics of the singing scene UI that were proposed in this issue.
Further improvements to this can be done in more specific issues. So I will close this now.
