### ISSUE TITLE
Change Player Settings to ".NET Standard 2.0" ?

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#88]
### Problem or question to be solved

I noticed that the Player Settings are set to ".NET 4.x". I switched to ".NET Standard 2.0" without any issues. The current code base seems to work perfectly fine.

UltraStar Play is targeting many different factors. Using .NET 2.0 might be advantageous.

Should we change the setting to .NET 2.0 or leave it at .NET 4.x ?

**Comment by basisbit** [comment]
- .net 4 as target is required for the mocking framework to properly write fast and small unit tests
- .net 4 as target is required to use the incremental garbage collection instead of stop-the-world garbage collection when heap needs to be cleaned

**Comment by basisbit** [comment]
`Using .NET 2.0 might be advantageous.`
Please describe those advantages. Since we are using Unity 2019, there should be almost no disadvantages afaik.
Also, .net 2.0 framework has nothing to do with .net core 2.

**Comment by achimmihca** [comment]
I see. Then my concerns were invalid. I will close the issue.
