### ISSUE TITLE
Preview of music and video in SongSelectScene

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#89]
### Actual behaviour

The SongSelectScene is showing covers and song title. However, neither the video nor the music is played at the moment.

### Expected behaviour

Just like in USDX, the video and music should be started somewhere in the middle of the song when a song is selected.

Note that some songs have tags in the txt file that define "previewstart" and "previewend"

**Comment by basisbit** [comment]
For songs where no #PREVIEWSTART or #PREVIEWEND tag is set, the preview should start at some place where there are actually pitches to sing, instead of a random place where maybe there is only some background music for the next X seconds.

**Comment by bohning** [comment]
There’s actually a #PREVIEWEND tag? I have not once seen it in any file.

**Comment by basisbit** [comment]
The song Preview should start only when the last song selction change was at least 0.5 seconds ago, and not before the background-songs-scanning is finished. It is important that the code related to the song preview does not slow down fast scrolling through the songs or the search or the initial song loading.

**Comment by achimmihca** [comment]
> The song Preview should start [...] not before the background-songs-scanning is finished. It is important that the code related to the song preview does not slow down fast scrolling through the songs or the search or the initial song loading.

Song preview does not wait for all songs to be found. This would be inconsistent. Furthermore it is not necessary because the audio is streamed such that impact on performance is minimal.
