### ISSUE TITLE
Add more options (general volume, preview volume, ...)

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#90]
### Actual behaviour

The SoundOptionsScene are empty and also some other options are missing.

### Expected behaviour

There should be options for the general volume and preview volume.
Note that at the moment there is no song preview (see #89) but the option can be prepared nonetheless. 

It would also be nice to have some options for the SingScene. For example, debug options to enable / disable the grid of beats and lyrics on the notes.
Maybe the debug options do not need an in-game UI. It could be sufficient to enable them in the Settings.json file.

**Comment by basisbit** [comment]
Indeed, the game should have more settings where required. In general, we should aim for not adding too many settings, and thus look at the use cases where extra settings would be required.
Adding settings just to the Settings.json would make it very difficult for mobile device users to change these settings. Also, the experience from USDX tells that for every setting that is implemented only in the settings-file, someone eventually will create a feature request to have that setting in game-ui. Maybe having a long list of settings in an advanced settings scene would solve that,

For what use case would a user need a general volume control in the game settings? Doesn't every device already have its own system volume control exactly for that?

**Comment by achimmihca** [comment]
> For what use case would a user need a general volume control in the game settings? Doesn't every device already have its own system volume control exactly for that?

On a second thought, you could be right. Windows lets you control the volume for every app I think.
Still, I would expect such a feature. All games I now have a volume control. Implementing it should be as simple as setting AudioListener.volume.

**Comment by achimmihca** [comment]
What could be added as well is an option to toggle the background music (that is played in the menu).
However, this should be implemented *after* background music has been added.

**Comment by achimmihca** [comment]
I will close this issue now. Other options (such as background music) can be added as needed
