### ISSUE TITLE
Mutable song data structure for song editor ?

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#93]
### Problem or question to be solved

For the song editor, there is a need for a song data structure that can be modified and loaded and saved in an unfinished state.
The data structure will have some fields that are specific to the editor, and not for the sing scene (for example, I want to have something like a "layer" for a note that can be toggle visible/invisible).

Because an unfinished or broken song can be saved and loaded (it is just a txt file, anything is possible), errors and warnings of the song have to be collected (instead of rejecting the song file). I want to show errors / warnings of a song in the editor similar to how your IDE is showing issues with your code.

My question is whether the required fields and features should be added to the current SongMeta, Voice, Sentence and Note classes or if dedicated versions of these classes should be created for the editor.

### Your opinion on the topic

I would try to re-use the existing data structures.

**Comment by basisbit** [comment]
It is rather easy to make sure the editor will never write invalid song files, thus we probably do not need to write a backup file. 
Regarding the data structures: in best case, they are just simple plain old c# objects / beans, so there is no problem with making them writable. Creation of them should still be handled by some factory or similar mechanism that checks validity and is optimized for maximum performance.
